<font face="微软雅黑" color=green size=5>Python数据分析</font>

# numpy基础

numpy的核心特征之一就是N维数组对象ndarray，ndarray是python中一个快速，灵活的大型数据集容器，它包含的每一个元素均为相同类型。

In [6]:
import numpy as np

shape 用来表征数组每一维度的数量 数组名.shape  
dtype 用来描述数组的数据类型 数组名.dtype  
ndim 用来查看维度

## 生成数组

array() np.array(变量名) np.array(list) 将列表转换成数组  
zeros() 一次性创造全是0的数组 np.zeros(数字) 一维 np.zeros((n, m)) n×m数组  
ones() 一次性创造全是1的数组  用法同zeros()  
empty() 创建一个没有初始化数值的数组 用法同zeros()  

## 索引与切片

一维数组  
数组名[n] 索引n处的值，一维数组索引与列表相同，可看成是列表  
数组名[n:m] 索引n到m-1处的值，如果是高维，返回n到m-1行的数组  

二维数组，每个索引值对应的元素不再是一个值，而是一个一维数组    
数组名[n][m] 单个元素n,m处  
数组名[n,m] 单个元素n,m处  
数组名[n] 第n行元素

多维数组  
数组名[n] 返回的对象是一个降低一个维度的数组，每个平面的第n行组成的二维数组  
数组名[n,m] 返回一个一维数组  
数组名[n1:n2, m1:m2] 返回n1到n2-1行，m1到m2-1列的数组  

## 神奇索引

为了选出一个符合特定顺序的子集，可以通过传递一个包含指明所需顺序的列表或数组来完成。  
数组名[[n]] 提取第n行的数组  
数组名[[n1,n2,n3]] 提取索引为n1,n2,n3行的数组  
数组名[[n1,n2,n3],[m1,m2,m3]] 提取索引为(n1,m1),(n2,m2),(n3,m3)的元素

## 数组转置

数组名.T  
矩阵内积 np.dot(arr.T,arr)  
arange python内建函数range的数组版，返回一个数组，np.arange(n) n从0开始，到n-1结束。  
transpose 置换轴

## 通用函数

np.sqrt(数组名) 开方  
np.exp(数组名) 指数  
np.square(数组名) 平方  
np.add(x,y) 加  
np.multiply() 乘  
np.divide() 除  
np.where(条件,数组1,数组2) 类似三元表达式   
np.nan 代表NaN

In [3]:
arr = np.random.randn(4,4)
np.where(arr>0, 2, -2)

array([[-2, -2, -2, -2],
       [-2,  2,  2, -2],
       [ 2,  2, -2, -2],
       [-2,  2, -2,  2]])

## 数学与统计方法

数组名.sum(axis=0或1) 或np.sum(数组名) 求和   
数组名.mean() 平均值  
数组名.std() 标准差  
数组名.var() 方差  
axis=0 对行进行操作，等价于DataFrame中 axis='index'  
axis=1 对列进行操作，等价于DataFrame中 axis='columns'  
axis=i 沿着第i个下标变化的方向进行操作   
数组名.sort() 或np.sort(数组名) 排序升序  
np.argsort(数组名) 返回排序后的索引  
np.sort(数组名)[::-1] 降序排列  
np.flipub(数组名) 翻转元组，也可以用数组名[::-1]
np.random.seed(1) 随机种子  
np.random.rand((n,m)) 从均匀分布中抽取样本生成n×m的数组  
np.random.randn((n,m)) 从标准正态分布中抽取样本生成n×m的数组 

## 重塑数组

很多情况下，将数组从一个形状转换为另一个形状，并且不复制任何数据，可以用reshape方法。

In [7]:
arr = np.arange(8)
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [13]:
arr.reshape(4, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

数组新的shape属性应该要与原来的配套，如果等于-1的话，那么Numpy会根据剩下的维度计算出数组的另外一个shape属性值。

In [9]:
arr.reshape(-1, 1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7]])

In [12]:
arr.reshape(1, -1)

array([[0, 1, 2, 3, 4, 5, 6, 7]])

In [14]:
arr.reshape(2, -1)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

将更高维的数组转换为一维数组（扁平化、分散化）。

In [7]:
arr.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7])

In [8]:
arr.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7])

## 复制数组

np.tile() 把数组沿各个方向复制

In [9]:
a = np.array([0,1,2])
np.tile(a,(2,1)) #把a先沿x轴复制1倍，再把结果沿y轴复制两倍

array([[0, 1, 2],
       [0, 1, 2]])

In [10]:
np.tile(a, 2) #沿x轴复制2倍

array([0, 1, 2, 0, 1, 2])

np.linspace() 创建等差数列

In [11]:
np.linspace(0,10,11) #第一个起始值，第二个终点值，第三个数量

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

## 连接和分割数组

1、np.concatenate() 可以获取数组的序列，并沿着输入轴将他们按顺序连接在一起。

In [13]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[7,8,9],[10,11,12]])
np.concatenate([arr1,arr2],axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [14]:
np.concatenate([arr1,arr2],axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

2、split可以将数组沿轴向切片成多个数组。

In [16]:
np.split(arr1,[1,2]) #[1,2]表示将数组拆分时的索引位置

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([], shape=(0, 3), dtype=int32)]

3、数组后面追加数组

In [17]:
np.append(arr1,arr2,axis=0) #按行追加

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

## broadcast（广播机制）

广播”指的是在不同维度的数组之间进行算术运算的一种执行机制，其通过将数据矢量化进行高效的运算。

通常只在对多个数组进行对应元素操作形状不同时，才会发生广播。
那什么是对应元素进行操作呢？比如：

In [5]:
a = np.array([1,2,3])
b = np.array([2,2,2])
a*b 
# a和b对应元素相乘
# a*b的结果是： [1*2,2*2,3*2]

array([2, 4, 6])

什么叫做形状不同呢？

In [7]:
a = np.array([1,2,3])
b = 2
a*b #a是1维向量，b是标量，这就是形状不同
# 结果也是：[1*2,2*2, 3*2]

array([2, 4, 6])

这是因为发生了广播。b被填充为[2,2,2]
然后a\*b的效果变成了，[1,2,3]*[2,2,2]

可以广播的几种情况：

假定只有两个数组进行操作，即A+B、A*B这种情况。

**两个数组各维度大小从后往前比对均一致**

In [8]:
A = np.zeros((2,5,3,4))
B = np.zeros((3,4))
print((A+B).shape) # 输出 (2, 5, 3, 4)

A = np.zeros((4))
B = np.zeros((3,4))
print((A+B).shape) # 输出(3,4)

(2, 5, 3, 4)
(3, 4)


In [9]:
A = np.zeros((2,5,3,4))
B = np.zeros((3,3))
print((A+B).shape)

ValueError: operands could not be broadcast together with shapes (2,5,3,4) (3,3) 

为啥呢？因为最后一维的大小A是4，B是3，不一致。

**两个数组存在一些维度大小不相等时，有一个不相等数组的维度大小为1**

In [10]:
A = np.zeros((2,5,3,4))
B = np.zeros((3,1))
print((A+B).shape) # 输出：(2, 5, 3, 4)

A = np.zeros((2,5,3,4))
B = np.zeros((2,1,1,4))
print((A+B).shape) # 输出：(2, 5, 3, 4)

A = np.zeros((1))
B = np.zeros((3,4))
print((A+B).shape) # 输出(3,4)

(2, 5, 3, 4)
(2, 5, 3, 4)
(3, 4)


In [11]:
# 下面是报错案例
A = np.zeros((2,5,3,4))
B = np.zeros((2,4,1,4))
print((A+B).shape)

ValueError: operands could not be broadcast together with shapes (2,5,3,4) (2,4,1,4) 

为啥报错？因为A和B的第2维不相等。并且都不等于1.

**使用numpy的广播机制代替for循环以提高效率**

In [17]:
def contrast(n,f,k):
    import time
    data = np.random.rand(n, f)
    centers = data[:k]
    t1 = time.time()
    c1 = (data[:,:,None]-centers.T[None,:,:])**2
    t2 = time.time()
    print('cost of broadcast: ',str(t2-t1))
    c2 = np.ones((n,f,k))-1
    t1 = time.time()
    for i in range(n):
        for j in range(f):
            for g in range(k):
                c2[i,j,g] = (data[i,j]-centers[g,j])**2
    t2 = time.time()
    print('cost of _for_: ',str(t2-t1))
    print('c2 - c1 == 0?: ',str((c2-c1).all()==0))

def test_time_cost(n,f,k):
    contrast(n,f,k)

if __name__ == '__main__':
    test_time_cost(200000,5,10)

cost of broadcast:  0.042083740234375
cost of _for_:  4.9777257442474365
c2 - c1 == 0?:  True


## 数组增加维度

np.newaxis的作用就是在这一位置增加一个一维，这一位置指的是np.newaxis所在的位置

In [19]:
a = np.array([0.0, 10.0, 20.0, 30.0])
print(a.shape)
b = a[:, np.newaxis]
print(b.shape)
c = a[np.newaxis, :]
print(c.shape)

(4,)
(4, 1)
(1, 4)


### newaxis本质

np.newaxis 在使用和功能上等价于 None，其实就是 None 的一个别名。

In [20]:
type(np.newaxis)

NoneType

In [21]:
np.newaxis == None

True

In [22]:
b = a[:, np.newaxis]
b

array([[ 0.],
       [10.],
       [20.],
       [30.]])

In [23]:
b = a[:, None]
b

array([[ 0.],
       [10.],
       [20.],
       [30.]])

### 索引多维数组的某一列时返回的是一个行向量

In [24]:
X = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
X[:, 1] #这里是一个行

array([ 2,  6, 10])

如果我索引多维数组的某一列时，返回的仍然是列的结构，一种正确的索引方式是：

In [25]:
X[:, 1][:, np.newaxis]

array([[ 2],
       [ 6],
       [10]])

如果想实现第二列和第四列的拼接（层叠）：

In [26]:
X_sub = np.hstack([X[:, 1][:, np.newaxis], X[:, 3][:, np.newaxis]])   
X_sub

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

当然更为简单的方式还是使用切片：

In [27]:
X[:, [1, 3]]

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

## 数组去重

对于一维数组或者列表，np.unique() 函数 去除其中重复的元素 ，并按元素 由小到大 返回一个新的无元素重复的元组或者列表。

`numpy.unique(arr, return_index, return_inverse, return_counts)
`

arr：输入数组，如果不是一维数组则会展开
return_index：如果为 true，返回新列表元素在旧列表中的位置（下标），并以列表形式存储。
return_inverse：如果为true，返回旧列表元素在新列表中的位置（下标），并以列表形式存储。
return_counts：如果为 true，返回去重数组中的元素在原数组中的出现次数。

In [2]:
import numpy as np
A = [1, 2, 2, 5, 3, 4, 3]
a = np.unique(A)
print(a)
print("______")

a, indices = np.unique(A, return_index=True)   # 返回新列表元素在旧列表中的位置（下标）
print(a)		 # 列表
print(indices)	 # 下标
print("______")

a, indices = np.unique(A, return_inverse=True)   # 旧列表的元素在新列表的位置
print(a)
print(indices)
print(a[indices])     # 使用下标重构原数组
print("______")

unique, counts = np.unique(A, return_counts=True)    # 每个元素在旧列表里各自出现了几次
print(dict(zip(unique, counts)))
print("______")

B = ([1, 2], [2, 5], [3, 4])
b = np.unique(B)
C= ['fgfh','asd','fgfh','asdfds','wrh']
c= np.unique(C)
print(b)
print(c)

[1 2 3 4 5]
______
[1 2 3 4 5]
[0 1 4 5 3]
______
[1 2 3 4 5]
[0 1 1 4 2 3 2]
[1 2 2 5 3 4 3]
______
{1: 1, 2: 2, 3: 2, 4: 1, 5: 1}
______
[1 2 3 4 5]
['asd' 'asdfds' 'fgfh' 'wrh']


# Pandas入门

pandas采用了很多numpy的代码风格，但最大的不同在于pandas是用来处理表格型或异质型数据的，而numpy更适合处理同质型的数值类数组数据。

In [2]:
import pandas as pd
from pandas import DataFrame, Series

## Series

Series是一种一维的数组型对象，它包含了一个值序列，并且包含了数据标签，成为索引，最简单的序列可以仅仅由一个数组组成。

In [3]:
obj = pd.Series([4,7,-5,None], index = ['d','b','a','c'])
obj

d    4.0
b    7.0
a   -5.0
c    NaN
dtype: float64

交互式环境中Series的字符串表示，索引在左边，值在右边，可通过values属性和index属性分别获得Series对象的值和索引。

In [3]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [4]:
obj.index

Index(['d', 'b', 'a', 'c'], dtype='object')

可以使用字典生成一个Series，pd.Series(字典)。

Series的索引可以通过按位置赋值的方式进行改变，obj.index = [值]。

## DataFrame

DataFrame表示的是矩阵的数据表，它包含已排序的列集合，每一列可以是不同的值类型，DataFrame既有行索引，也有列索引，DataFrame是二维的。

### 构建DataFrame

有多种方式构建DataFrame，其中最常用的是利用包含等长度列表或numpy数组的字典来形成。行索引（index），列索引（columns），值（values）。

In [3]:
data = {'state':['ohio', 'ohio', None],
        'year':[None, 2001, 2001]}
frame = pd.DataFrame(data)
frame

state    year
0  ohio     NaN
1  ohio  2001.0
2  None  2001.0

In [17]:
frame['year'].values

array([  nan, 2001., 2001.])

### DataFrame切片

1、DataFrame的列会按照指定顺序排列，如果你指定了列的顺序。

In [3]:
pd.DataFrame(data, columns = ['year', 'state'])

year   state
0  2000    ohio
1  2001    ohio
2  2002  nevada

2、DataFrame中的一列，可以按照字典型标记，或属性那样检索为Series。

In [9]:
frame['state']

0      ohio
1      ohio
2    nevada
Name: state, dtype: object

3、行可以通过位置或特殊属性loc进行选取。

In [10]:
frame.loc[0]

state    ohio
year     2000
Name: 0, dtype: object

4、列的引用可以修改，可以对列赋值为标量或值数组，如果被赋值的列不存在，则会生成一个新列。

In [14]:
frame['debt'] = 16.5
frame

state  year  debt
0    ohio  2000  16.5
1    ohio  2001  16.5
2  nevada  2002  16.5

5、del关键字可以像在字典中那样删除列。

In [15]:
del frame['debt']
frame

state  year
0    ohio  2000
1    ohio  2001
2  nevada  2002

In [16]:
frame.T #转置

0     1       2
state  ohio  ohio  nevada
year   2000  2001    2002

6、DataFrame的values属性会将包含在DataFrame中的数据以二维数组的形式返回。

In [17]:
frame.values

array([['ohio', 2000],
       ['ohio', 2001],
       ['nevada', 2002]], dtype=object)

In [18]:
frame.columns #列索引

Index(['state', 'year'], dtype='object')

In [19]:
frame.index #行索引

RangeIndex(start=0, stop=3, step=1)

7、pandas索引对象可以包含重复标签。

In [20]:
labels = pd.Index(['foo','foo','bar','bar'])

8、显示DataFrame的行数

In [21]:
frame.head(2)

state  year
0  ohio  2000
1  ohio  2001

### 列转行

In [4]:
pd.melt(frame, id_vars=['state'], value_vars=['year'])

state variable  value
0    ohio     year   2000
1    ohio     year   2001
2  nevada     year   2002

In [5]:
pd.melt(frame, value_vars=['state', 'year'])

variable   value
0    state    ohio
1    state    ohio
2    state  nevada
3     year    2000
4     year    2001
5     year    2002

### 重建索引

reindex是pandas对象的重要方法，该方法用于创建一个符合新索引的新对象。（标签唯一）

In [4]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6],index = ['d', 'b', 'a', 'c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [5]:
obj.reindex(['a', 'b', 'c', 'd'])

a   -5.3
b    7.2
c    3.6
d    4.5
dtype: float64

series调用reindex方法时，会将数据按照新的索引（行索引或列索引）进行排列，如果某个索引值之前并不存在，则会引入缺失值。

### 新增列

In [ ]:
frame["month"] = 1

### 删除行

drop方法会返回一个含有指示值或轴向上删除值的新对象。

In [28]:
obj = pd.Series(np.arange(5.),index = ['a','b','c','d','e'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [29]:
obj.drop('c')

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

**在DataFrame中，索引值可以轴向上删除，在调用drop时使用标签序列会根据行标签删除值。名字.drop(行标签)**

### 删除列

可以通过传递axis=1或axis='columns'来从列中删除值。

名字.drop(列名,axis=1)#删除这一列  
名字.drop([,,],axis='columns')#删除多列

### 重命名

In [9]:
# 修改列名
frame.columns = ["A", "B"]
frame

A       B
0  ohio     NaN
1  ohio  2001.0
2  None  2001.0

In [10]:
# 同时修改行名和列名
df_re=frame.rename(columns={"A": "a", "B": "c"},index={0:"0a",1:"1a"})
df_re

a       c
0a  ohio     NaN
1a  ohio  2001.0
2   None  2001.0

### 索引，选择与过滤

1、Series的索引与Numpy数组索引的功能类似。

In [30]:
obj = pd.Series(np.arange(4),index = ['a','b','c','d'])
obj

a    0
b    1
c    2
d    3
dtype: int32

In [31]:
obj['b']

1

In [32]:
obj[1]

1

In [33]:
obj[2:4]

c    2
d    3
dtype: int32

2、使用单个值或序列，可以从DataFrame中索引出一个或多个列。

In [5]:
data = {'state':['ohio', 'ohio', 'nevada'],
        'year':[2000, 2001, 2002]}
frame = pd.DataFrame(data)
frame

state  year
0    ohio  2000
1    ohio  2001
2  nevada  2002

In [35]:
frame['year'] #索引单个列

0    2000
1    2001
2    2002
Name: year, dtype: int64

In [36]:
frame[['year','state']] #索引多个列

year   state
0  2000    ohio
1  2001    ohio
2  2002  nevada

3、使用布尔值DataFrame进行索引，布尔值DataFrame可以是对标量值进行比较产生。

data[data>5]=0  将大于5的变为0，其余不变

4、通过标签选出单行多列或多行多列的数据，轴标签loc，整数标签iloc。

frame.loc[行标签,列标签]

In [39]:
frame.loc[0,'year']#单行单列

2000

In [40]:
frame.loc[0,['year','state']]#单行多列

year     2000
state    ohio
Name: 0, dtype: object

In [41]:
frame.loc[[0,1],'year']#多行单列

0    2000
1    2001
Name: year, dtype: int64

frame.iloc[行索引值,列索引值]

In [42]:
frame.iloc[0,0]

'ohio'

### 算术与数据对齐

1、add 加 sub 减 div 除 mul乘  
a.add(b,axis=0) 行相加

2、函数应用和映射

In [48]:
f = lambda x: x.count()
frame.apply(f,axis='columns') #以列作为索引的Series，默认是axis=0

0    2
1    2
2    2
dtype: int64

3、排序

如需按行或列索引进行排序，需要使用sort_index方法，默认为升序排列。

In [49]:
frame.sort_index()#按行索引

state  year
0    ohio  2000
1    ohio  2001
2  nevada  2002

In [51]:
frame.sort_index(axis=1, ascending=False)#按列索引并且降序排列

year   state
0  2000    ohio
1  2001    ohio
2  2002  nevada

如需根据Series的值进行排序，使用sort_values方法。当对DataFrame排序时，可以使用一列或多列作为排序键，使用参数by实现。

In [53]:
frame.sort_values(by='year',ascending=False)

state  year
2  nevada  2002
1    ohio  2001
0    ohio  2000

In [54]:
list(frame) #获得表头

['state', 'year']

### 描述性统计

pandas对象装配了一个常用数学，统计学方法的集合，与numpy中的类似方法相比，它们内建了处理缺失值的功能，NA值会被自动排除。

In [56]:
frame.sum(axis=0) #行相加

state    ohioohionevada
year               6003
dtype: object

In [57]:
frame.describe()#描述性统计

year
count     3.0
mean   2001.0
std       1.0
min    2000.0
25%    2000.5
50%    2001.0
75%    2001.5
max    2002.0

常见方法：count\min\max\sum\mean\median\var\std

In [59]:
frame.apply(pd.value_counts).fillna(0) #计算不同值在每个列中出现的次数

state  year
2000      0.0   1.0
2001      0.0   1.0
2002      0.0   1.0
nevada    1.0   0.0
ohio      2.0   0.0

### 数据类型转换

In [60]:
frame.dtypes #查看数据框的类型

state    object
year      int64
dtype: object

In [61]:
frame.info() #查看数据框的更多详细信息

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   state   3 non-null      object
 1   year    3 non-null      int64 
dtypes: int64(1), object(1)
memory usage: 176.0+ bytes


pandas三种常用的数据格式的转换：   
1、名字.astype()强制转化为数据类型  
2、通过创建自定义的函数进行数据转换  
3、pandas提供的to_numeric()以及to_datetime()

In [79]:
frame['year'] = frame['year'].astype('int')#将DataFrame中的某一列转换类型
frame

state  year
0    ohio  2000
1    ohio  2001
2  nevada  2002

### 数据类型筛选

In [3]:
frame.dtypes #查看数据框的类型

state    object
year      int64
dtype: object

In [4]:
frame.select_dtypes(include = ['int64','float64']) #选择包含int和float的数据

year
0  2000
1  2001
2  2002

In [5]:
frame.select_dtypes(include = 'object')

state
0    ohio
1    ohio
2  nevada

In [6]:
frame.select_dtypes(exclude = 'bool') #除布尔型之外的类型的数据

state  year
0    ohio  2000
1    ohio  2001
2  nevada  2002

### DataFrame拼接

In [91]:
data1 = {'state':['nace','eque'],
        'year':[2003,2004]}
frame1 = pd.DataFrame(data1)
frame1

state  year
0  nace  2003
1  eque  2004

In [92]:
frame.append(frame1, ignore_index=True) #忽略列名，只显示一个，也可用循环实现

state  year
0    ohio  2000
1    ohio  2001
2  nevada  2002
3    nace  2003
4    eque  2004

In [93]:
pd.concat([frame,frame1], axis=0)#横向拼接

state  year
0    ohio  2000
1    ohio  2001
2  nevada  2002
0    nace  2003
1    eque  2004

### 时间序列/差分

In [3]:
frame.shift(1)

state    year
0  None     NaN
1  ohio     NaN
2  ohio  2001.0

frame.shift(periods=1, freq=None, axis=0) periods类型为int，表示移动的幅度，可以是正数，也可以是负数，默认值为1，1表示移动一次，这里移动的是数据，而索引是不移动的，移动之后没有对应值的，为NaN。

freq可选参数，只适用于时间序列，如果这个参数存在，会按照参数值移动时间索引，而数据值没有发生变化。

In [14]:
frame[['year']].diff(periods=1) # 一阶差分

year
0   NaN
1   1.0
2   1.0

diff函数是从数学上来说，是将数据与平移后的数据进行比较得出的差异数据。从操作的意义上来说，是两条临近记录的差值，也就是一阶差分。

### 抽样

frame.sample(n=None, frac=None, replace=False, weights=None, random_state=None, axis=None)  
n：设置抽样数量  
frac：设置抽样比例  
replace：设置是否放回  
weights：设置样本权重  
random_state：设置随机种子

In [97]:
frame.sample(frac=0.5)

state  year
0  ohio  2000
1  ohio  2001

### set_index()

功能：指定数据表中的某列或指定某个数组列表为DataFrame行索引。  
函数语法  
DataFrame.set_index(keys, *, drop=True, append=False, inplace=False, verify_integrity=False)
 
参数说明

- key：数据表中的某列/列标签列表/数组列表，需要设置为索引的列。
- drop：删除用作新索引的列，默认为True，删除。
- append：是否将列附加到现有索引，默认为False，否。
- inplace：表示当前操作是否对原数据重新，默认为False，否。
- verify_integrity：检查新索引的副本。否则，请将检查推迟到必要时进行。将其设置为False，将提高该方法的性能，默认为False。

In [6]:
import pandas as pd
data = pd.read_csv('../data/energy.csv')
df = data.set_index('Unnamed: 0')
df

load   temp
Unnamed: 0                        
2012-01-01 00:00:00  2698.0  32.00
2012-01-01 01:00:00  2558.0  32.67
2012-01-01 02:00:00  2444.0  30.00
2012-01-01 03:00:00  2402.0  31.00
2012-01-01 04:00:00  2403.0  32.00
...                     ...    ...
2014-12-31 19:00:00  4012.0  18.00
2014-12-31 20:00:00  3856.0  16.67
2014-12-31 21:00:00  3671.0  17.00
2014-12-31 22:00:00  3499.0  15.33
2014-12-31 23:00:00  3345.0  15.33

[26304 rows x 2 columns]

### reset_index()

功能：第一种对原来的数据表进行reset，第二种是对使用过的set_index()函数进行reset。

函数语法

DataFrame.reset_index(level=None, \*, drop=False, inplace=False, col_level=0, col_fill=‘’, allow_duplicates=\_NoDefault.no_default, names=None)[source]

参数说明

- key：数值类型可以为：int、str、tuple或list，默认无。
- drop：当指定drop=False（默认为False）时，则索引列会被还原为普通列；否则，如设置为True，原索引列会被丢弃。
- inplace：表示当前操作是否对原数据重新，默认为False，否。
- col_level：数值类型为int或str，默认值为0，如果列有多个级别，则确定将标签插入到哪个级别。默认情况下，它将插入到第一级。
- col_fill：对象，默认‘’，如果列有多个级别，则确定其他级别的命名方式。如果没有，则重复索引名。

In [2]:
df.reset_index()

Unnamed: 0    load   temp
0      2012-01-01 00:00:00  2698.0  32.00
1      2012-01-01 01:00:00  2558.0  32.67
2      2012-01-01 02:00:00  2444.0  30.00
3      2012-01-01 03:00:00  2402.0  31.00
4      2012-01-01 04:00:00  2403.0  32.00
...                    ...     ...    ...
26299  2014-12-31 19:00:00  4012.0  18.00
26300  2014-12-31 20:00:00  3856.0  16.67
26301  2014-12-31 21:00:00  3671.0  17.00
26302  2014-12-31 22:00:00  3499.0  15.33
26303  2014-12-31 23:00:00  3345.0  15.33

[26304 rows x 3 columns]

### 打印数据框

In [3]:
display(df)

load   temp
Unnamed: 0                        
2012-01-01 00:00:00  2698.0  32.00
2012-01-01 01:00:00  2558.0  32.67
2012-01-01 02:00:00  2444.0  30.00
2012-01-01 03:00:00  2402.0  31.00
2012-01-01 04:00:00  2403.0  32.00
...                     ...    ...
2014-12-31 19:00:00  4012.0  18.00
2014-12-31 20:00:00  3856.0  16.67
2014-12-31 21:00:00  3671.0  17.00
2014-12-31 22:00:00  3499.0  15.33
2014-12-31 23:00:00  3345.0  15.33

[26304 rows x 2 columns]

### 排序

In [7]:
# 默认是升序排序(ascending=True),ascending=False:降序排序
df_sorted = df.sort_values(by='load', ascending=True)
df_sorted

load   temp
Unnamed: 0                        
2012-10-30 03:00:00  1979.0  60.00
2012-10-30 02:00:00  1987.0  59.33
2012-10-30 01:00:00  2026.0  60.00
2012-10-30 00:00:00  2064.0  59.67
2012-10-30 04:00:00  2067.0  59.67
...                     ...    ...
2013-07-19 17:00:00  5178.0  95.00
2013-07-19 13:00:00  5195.0  90.67
2013-07-19 14:00:00  5202.0  92.67
2013-07-19 15:00:00  5210.0  94.00
2013-07-19 16:00:00  5224.0  95.00

[26304 rows x 2 columns]

In [8]:
# 如果要使一列ascending为True,一列为False:
df_sorted = df.sort_values(by=['load', 'temp'], ascending=[True, False])
df_sorted

load   temp
Unnamed: 0                        
2012-10-30 03:00:00  1979.0  60.00
2012-10-30 02:00:00  1987.0  59.33
2012-10-30 01:00:00  2026.0  60.00
2012-10-30 00:00:00  2064.0  59.67
2012-10-30 04:00:00  2067.0  59.67
...                     ...    ...
2013-07-19 17:00:00  5178.0  95.00
2013-07-19 13:00:00  5195.0  90.67
2013-07-19 14:00:00  5202.0  92.67
2013-07-19 15:00:00  5210.0  94.00
2013-07-19 16:00:00  5224.0  95.00

[26304 rows x 2 columns]

## 常用函数

### map

map() 是一个Series的函数，DataFrame结构中没有map()。map()将一个自定义函数应用于Series结构中的每个元素(elements)。

In [5]:
data = {'state':['ohio', 'ohio', 'nevada'],
        'year':[2000, 2001, 2002]}
df = pd.DataFrame(data)
display(df)

state  year
0    ohio  2000
1    ohio  2001
2  nevada  2002

In [6]:
df["state"] = df["state"].map(str.capitalize) #首字母大写
display(df)

state  year
0    Ohio  2000
1    Ohio  2001
2  Nevada  2002

In [9]:
df = pd.DataFrame({'key1' : ['a', 'a', 'b', 'b', 'a'],
                   'key2' : ['one', 'two', 'one', 'two', 'one'],
                   'data1' : np.arange(5),
                   'data2' : np.arange(5,10)})
df

key1 key2  data1  data2
0    a  one      0      5
1    a  two      1      6
2    b  one      2      7
3    b  two      3      8
4    a  one      4      9

In [10]:
df['data1'] = df['data1'].map(lambda x : "%.3f"%x) #lambda在这里其实是在定义一个简单的函数，一个没有函数名的函数。
df

key1 key2  data1  data2
0    a  one  0.000      5
1    a  two  1.000      6
2    b  one  2.000      7
3    b  two  3.000      8
4    a  one  4.000      9

In [11]:
df['key1'] = df['key1'].map({'a':'c',"b":"d"})
df

key1 key2  data1  data2
0    c  one  0.000      5
1    c  two  1.000      6
2    d  one  2.000      7
3    d  two  3.000      8
4    c  one  4.000      9

### apply

apply() 函数功能是自动遍历Series 或者 DataFrame，对每一个元素运行指定的函数。 对于Series 元素为Series中的每一个值，对于DataFrame元素为DataFrame的一行（axis=1）或一列（axis=0），map、transformer只能进行一列处理处理，apply()可以对单列或多列进行处理.

In [13]:
df = pd.DataFrame({'key1' : ['a', 'a', 'b', 'b', 'a'],
                   'key2' : ['one', 'two', 'one', 'two', 'one'],
                   'data1' : np.arange(5),
                   'data2' : np.arange(5,10)})
df

key1 key2  data1  data2
0    a  one      0      5
1    a  two      1      6
2    b  one      2      7
3    b  two      3      8
4    a  one      4      9

In [14]:
df['total'] = df[['data1','data2']].apply(lambda x : x.sum(),axis=1 ) 
df

key1 key2  data1  data2  total
0    a  one      0      5      5
1    a  two      1      6      7
2    b  one      2      7      9
3    b  two      3      8     11
4    a  one      4      9     13

In [15]:
df.loc['total'] = df[['data1','data2']].apply(lambda x : x.sum(),axis=0 )
df

key1 key2  data1  data2  total
0        a  one    0.0    5.0    5.0
1        a  two    1.0    6.0    7.0
2        b  one    2.0    7.0    9.0
3        b  two    3.0    8.0   11.0
4        a  one    4.0    9.0   13.0
total  NaN  NaN   10.0   35.0    NaN

## 表达式计算

### query

DataFrame.query(expr, inplace=False, \**kwargs)  
其中的参数：

expr：str，要计算的查询字符串  
inplace，bool，查询结果是就地修改数据还是返回修改后的副本  
\**kwargs：pandas.eval() 支持的关键字参数，可用于查询

返回：

DataFrame：由提供的查询表达式生成的 DataFrame  
None：如果 inplace=True，但原数据被就地修改

支持以下算术运算：+, -, \*,/, \**, %, //（仅限 python 引擎）以及以下布尔运算： | (or), & (and), 和 ~ (not)。此外，“pandas”解析器允许使用 and、or 和 not，其语义与相应的位运算符不同。

In [6]:
df = pd.DataFrame({"a": [4, 3, 2], "b": [4, 5, 7], "c": [6, 8, 9]})
df

a  b  c
0  4  4  6
1  3  5  8
2  2  7  9

In [7]:
# pure python
df[(df['a'] < df['b']) & (df['b'] < df['c'])]

a  b  c
1  3  5  8
2  2  7  9

In [8]:
# query
df.query('(a < b) & (b < c)')

a  b  c
1  3  5  8
2  2  7  9

In [9]:
# a 列中有 b 列内容的
df.query('a in b')

a  b  c
0  4  4  6

In [10]:
# Python 方法，同上
df[df['a'].isin(df['b'])]

a  b  c
0  4  4  6

In [11]:
df.query('a not in b')

a  b  c
1  3  5  8
2  2  7  9

In [12]:
# Python 方法
df[~df['a'].isin(df['b'])]

a  b  c
1  3  5  8
2  2  7  9

### eval

语法为：

pd.eval(expr: 'str | BinOp',
      parser: 'str' = 'pandas',
      engine: 'str | None' = None,
      truediv=<no_default>,
      local_dict=None,
      global_dict=None,
      resolvers=(), level=0,
      target=None,
      inplace=False)  
参数详解：  

expr : str，要计算的表达式此字符串，不能包含任何 Python 语句（statements），仅包含 Python 表达式（expressions）。  

parser : {'pandas', 'python'}, 默认 'pandas'，用于从表达式构造语法树的解析器。默认 'pandas' 与标准 Python 代码略有不同， Python 解析器保留严格的 python 语义。  

engine : {'python', 'numexpr'}, 默认 'numexpr'，用于计算表达式的引擎。支持的引擎是：  
None : 尝试使用 numexpr，失败后回退到 python  
'numexpr': 此默认引擎使用 numexpr 用于复杂表达式中的大加速大 DataFrame  
'python': 就像 Python 的 eval 一样执行操作，一般不太有用。  
pandas 将来可能会有更多的后端引擎可用。  

truediv : bool, 可选，是否使用真除法，在 pandas 1.0.0 中移除（不要再使用）  

local_dict : dict 或者 None, 可选，局部变量字典，默认情况下取自 locals()  

global_dict : dict 或者 None, 可选，全局变量字典，默认情况下取自 globals()  

resolvers : list of dict-like（映射列表） 或者 None, 可选，方法解析器。实现 __getitem__特殊方法的对象列表，这些对象你可以注入其他命名空间用于变量查找。 比如， ~DataFrame.query 的方法注入 DataFrame.index 和 DataFrame.columns引入各自的变量到 ~pandas.DataFrame 的实例属性  

level : int, 可选。要遍历并添加到当前堆栈数据框的先前堆栈帧数范围，大多数用户不需要更改此参数

target : object, 可选, 默认为 None，这是赋值的目标对象。它是在有需要时使用的表达式中的变量赋值，如果这样，那么“target”必须支持使用字符串键分配项目，如果正在创建副本返回时，它还必须支持 .copy()    

inplace : bool, 默认 False，如果提供了'target'，并且表达式变异为'target'，则在原地修改'target'。否则，返回带有变异的数据  
返回：  

ndarray, numeric scalar, DataFrame, Series, 或者 None  
计算给定代码的完成值，如果 inplace=True，则为 None  
注：算术%运算中涉及的任何对象的数据类型都递归转换为 float64。  

In [13]:
df = pd.DataFrame({"animal": ["dog", "pig"], "age": [10, 20]})
df

animal  age
0    dog   10
1    pig   20

In [14]:
# 我们可以使用 pd.eval 添加一个新列：
pd.eval("double_age = df.age * 2", target=df)

animal  age  double_age
0    dog   10          20
1    pig   20          40

DataFrame.eval 描述对 DataFrame 列的操作的字符串进行计算。它仅对列进行操作，而不对特定行或元素进行操作。它允许 eval 运行任意代码，如果您将用户输入传递给此函数，这会使你容易受到代码注入的攻击，因此这个方法只能由你控制，不要开发给外部调用。

语法为：

DataFrame.eval(expr, inplace=False, **kwargs)  
参数：

expr : str，要计算的表达式字符串  
inplace : bool, 默认 False，如果表达式包含赋值，则是否执行操作替换并改变现有数据帧，否则返回一个新的数据帧  
**kwargs：传入pd.eval 的参数  
返回：  

计算结果，ndarray, scalar, pandas object, 或者 None  
如果inplace=True 则为 None

In [15]:
df = pd.DataFrame(dict(a=range(5), b=range(5, 10)))
df.eval("c = a + b", inplace=True)
df.eval("d = a + b + c", inplace=True)
df.eval("a = 1", inplace=True)
df

a  b   c   d
0  1  5   5  10
1  1  6   7  14
2  1  7   9  18
3  1  8  11  22
4  1  9  13  26

当 inplace 设置为 False（默认值）时，将返回具有新列或修改列的 DataFrame 的副本，并且原始帧不变。

支持以下算术运算：+, -, *,/, **, %, //（仅限 python 引擎）以及以下布尔运算： | (or), & (and), 和 ~ (not)。此外，“pandas”解析器允许使用 and、or 和 not，其语义与相应的位运算符不同。

pandas.eval() 支持这些操作：

    算术运算，除左移 (<<) 和右移 (>>) 操作, 如 df + 2 * pi / s ** 4 % 42 - the_golden_ratio  
    比较操作，包括链式比较，如 2 < df < df2  
    布尔运算，如 df < df2 and df3 < df4 or not df_bool  
    列表和元组字面量， 如 [1, 2] or (1, 2)  
    属性访问，如 df.a  
    下标表达式，如 df[0]  
    单变量评价计值，如 pd.eval("df") (这不是很有用)  
    数学函数，有 sin, cos, exp, log, expm1, log1p, sqrt, sinh, cosh, tanh, arcsin, arccos, arctan, arccosh, arcsinh, arctanh, abs, arctan2 和 log10  
不允许使用此 Python 语法：  

    表达式  
    函数调用（非以上说的数学函数）  
    is/is not 操作  
    if 表达式  
    lambda 表达式  
    list/set/dict 解析式  
    dict 和 set 字面量表达式  
    yield 表达式  
    生成器表达式  
    仅由标量值组成的布尔表达式  
    语句  
    不允许使用简单或复合语句，这包括 for、while 和 if  

必须通过在名称前面放置 @ 字符来显式引用要在表达式中使用的任何局部变量。例如：

In [16]:
df = pd.DataFrame(np.random.randn(5, 2), columns=list("ab"))
newcol = np.random.randn(len(df))

# 变量 newcol 参考计算
df.eval("b + @newcol")

0   -1.350336
1   -0.563354
2    0.532087
3   -1.663400
4   -0.520031
dtype: float64

如果不在局部变量前面加 @，pandas 将引发异常，告诉您该变量未定义。当使用数据帧时。DataFrame.eval() 和 DataFrame.query() 允许您在表达式中具有相同名称的局部变量和DataFrame 列。

In [17]:
a = np.random.randn()
df.query("@a < a")

a         b
0  0.582290 -0.164228
2 -0.173368  1.609626
4  0.942135 -0.449050

### df.query 与 df.eval 区别

df.query() 与 df.eval() 都可以用字符串表达式来对原数据做计算，区别主要有：

功能不同  
- df.query() 是数据查询，返回的符合条件的整行  
- df.eval() 是计算，根据表达式计算出任意结果  

表达式返回值要求不同  

- df.query() 由于是查询，需要表达式返回一个同长度同索引的布尔序列，为 True 的为筛选中的行  
- df.eval() 对表达式返回值没有要求，可以是任意结果，同时它会把表达式结果原样返回为最终结果  
- 另外 df.eval() 和 pd.eval() 的命名空间不同， pd.eval() 可以做任何事情，包括对数据的修改、非 pandas 数据的操作。如果要对 pandas 数据进行操作，要指定数据变量（如 df.col）。

# 数据载入、存储和文件格式

## 基本操作

1、将表格型数据读取为DataFrame对象是pandas的重要特征，read_csv和read_table是使用最多的函数。

`df = pd.read_csv('文件名', sep=',', header=None, chunksize=1000, encoding='gbk', parse_dates={'Date': [0, 1, 2]})`  
sep用于分隔每行字段的字符序列  
header显示列名  
encoding 显示文字类型 gbk表示中文  
chunksize用于迭代的块的大小  
parse_dates将表中0、1和2的时间列合并为新的Date列

2、将数据写入文本格式  

`frame.to_csv('路径',sep=' ', na_rep='NULL', index=False, header=False, columns=[,,], mode='a')  `  
sep=' '空格形式写入  
na_rep 对缺失值进行标注  
columns 按照选定的顺序写入  
mode='a' 不覆盖追加数据  
index=False  保存时不保存index

3、读入其他数据

Json数据 pd.read_json()  
Html数据 pd.read_html()  
Excel数据 pd.read_excel('路径','表名') 数据名称.to_excel('路径','表名')

4、数据库读数

In [98]:
import pymysql

具体见mysql数据库.ipynb资料

## 遍历文件夹及其子目录

In [99]:
import os

os.listdir(path) 返回指定的文件夹包含的文件或文件夹的名字的列表

os.walk(top, topdown=True, onerror=None, followlinks=False)  
top是你要遍历的目录的地址  
topdown为真，优先遍历top目录，否则优先遍历top的子目录  
followlinks为真，会遍历目录下的快捷方式  

os.walk的返回值是一个生成器，需要不断遍历，每次遍历的对象都是返回一个三元组(root, dirs, files)  
root：当前目录  
dirs：该文件夹中所有的目录的名字 list格式  
files：该文件夹中的所有文件 list格式  
每次用next()取得一个返回值。

os.path_join(path1,path2,...) 把目录和文件名合成一个路径  
os.mkdir(path) 创建一个目录  

In [101]:
import shutil

suhtil.copyfile(src, dst) 将src文件内容复制到dst文件中

# 数据清洗与准备

## 处理缺失值

pandas对象的所有描述性统计信息默认情况下是排除缺失值(NA)。

1、NA处理方法  
dropna() 返回所有的非空数据  
fillna() 用某些值填充缺失的数据或使用插值方法  
isnull() 返回表名哪些值是缺失值的布尔值  
notnull() isnull()的反函数  

In [102]:
frame.isnull().any() #判断哪些列存在缺失值

state    False
year     False
dtype: bool

In [103]:
frame.isnull().sum(axis=1) #返回每行缺失值总数

0    0
1    0
2    0
dtype: int64

In [104]:
frame.isnull().sum(axis=0) #返回每列缺失值总数

state    0
year     0
dtype: int64

In [ ]:
frame[frame.isnull().T.any()].index # 返回缺失值对应行索引

2、np.nan表示缺失值或 from numpy import nan as NA，用NA代替缺失值

3、当处理DataFrame对象时，dropna默认情况下会删除包含缺失值的行  
dropna(how='all') 删除所有值均为NA的行  
dropna(axis=1) 删除包含缺失值的列

## 补全缺失值

1、大多数情况下，主要使用fillna()来补全缺失值，可以使用一个常数来替代缺失值。

In [105]:
frame.fillna(0)

state  year
0    ohio  2000
1    ohio  2001
2  nevada  2002

2、在调用fillna时使用字典，可以为不同列设定不同的填充值。

In [106]:
frame.fillna({1:0.5, 2:0.7}) #第二列缺失值填充为0.5，第三列填充为0.7

state  year
0    ohio  2000
1    ohio  2001
2  nevada  2002

3、可以将平均值、中位数等函数计算结果用于填充缺失值。

In [107]:
frame.fillna(frame.mean())

state  year
0    ohio  2000
1    ohio  2001
2  nevada  2002

## 删除重复值

In [108]:
frame.drop_duplicates() #去除重复行

state  year
0    ohio  2000
1    ohio  2001
2  nevada  2002

In [109]:
frame.drop_duplicates(['state']) #基于指定列去除重复值

state  year
0    ohio  2000
2  nevada  2002

## 替代值

In [110]:
frame.replace(2000,np.nan)

state    year
0    ohio     NaN
1    ohio  2001.0
2  nevada  2002.0

In [111]:
frame.replace([2000,1000],[np.nan,0]) #多值替代

state    year
0    ohio     NaN
1    ohio  2001.0
2  nevada  2002.0

## 重命名轴索引

In [113]:
frame.rename(index={0:'zero',1:'one',2:'two'}, columns={'year':'years','state':'states'})

states  years
zero    ohio   2000
one     ohio   2001
two   nevada   2002

## 离散化和分箱

In [114]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]
bins = [18, 25, 35, 60, 100]#将年龄划分区间
cuts = pd.cut(ages, bins)
cuts

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [115]:
pd.value_counts(cuts)#统计区间个数

(18, 25]     5
(25, 35]     3
(35, 60]     3
(60, 100]    1
dtype: int64

In [116]:
pd.qcut(ages, 4)#将样本按四分位数切成四分

[(19.999, 22.75], (19.999, 22.75], (22.75, 29.0], (22.75, 29.0], (19.999, 22.75], ..., (29.0, 38.0], (38.0, 61.0], (38.0, 61.0], (38.0, 61.0], (29.0, 38.0]]
Length: 12
Categories (4, interval[float64]): [(19.999, 22.75] < (22.75, 29.0] < (29.0, 38.0] < (38.0, 61.0]]

# 重塑和透视

分层索引是pandas的重要特性，允许你在一个轴向上拥有多个索引层级，分层索引提供了一种在更低维度的形式中处理更高维度数据的方式。

In [119]:
frame.unstack() #拆堆

state  0      ohio
       1      ohio
       2    nevada
year   0      2000
       1      2001
       2      2002
dtype: object

In [120]:
frame.stack() #堆叠

0  state      ohio
   year       2000
1  state      ohio
   year       2001
2  state    nevada
   year       2002
dtype: object

# 绘图和可视化

## matplotlib库

In [117]:
import matplotlib as plt

## seaborn库

In [118]:
import seaborn as sns

# 数据聚合与分组操作

## groupby机制

DataFrame可以在它的行方向（axis=0）或列方向（axis=1）进行分组，在这种情况下，你可以传递列名或行名（无论它们是字符串、数字或其他python对象）作为分组键。

In [122]:
df = pd.DataFrame({'key1':['a','a','b','b','a'],
                   'key2':['one','two','one','two','one'],
                   'data1':np.random.randn(5),
                   'data2':np.random.randn(5)})
df

key1 key2     data1     data2
0    a  one -0.119439 -0.735122
1    a  two -0.813536  0.827313
2    b  one  0.332113 -0.439339
3    b  two  0.900853 -0.117592
4    a  one -0.459998  0.133810

1、根据key1标签计算data1的均值  

In [123]:
df.groupby('key1')['data1'].mean()

key1
a   -0.464324
b    0.616483
Name: data1, dtype: float64

2、根据key1，key2标签进行分组

In [124]:
df.groupby(['key1', 'key2'])

上述语句现在是一个groupby对象，需要迭代产生结果。

In [128]:
#当只有一个标签时：
for name, group in df.groupby('key1'):
    print(name)
    print(group)

a
  key1 key2     data1     data2
0    a  one -0.119439 -0.735122
1    a  two -0.813536  0.827313
4    a  one -0.459998  0.133810
b
  key1 key2     data1     data2
2    b  one  0.332113 -0.439339
3    b  two  0.900853 -0.117592


In [129]:
#当只有两个标签时：
for (k1,k2),group in df.groupby(['key1','key2']):
    print((k1,k2))
    print(group)

('a', 'one')
  key1 key2     data1     data2
0    a  one -0.119439 -0.735122
4    a  one -0.459998  0.133810
('a', 'two')
  key1 key2     data1     data2
1    a  two -0.813536  0.827313
('b', 'one')
  key1 key2     data1     data2
2    b  one  0.332113 -0.439339
('b', 'two')
  key1 key2     data1     data2
3    b  two  0.900853 -0.117592


根据key1，key2标签对data1进行分组，并求均值。

In [131]:
s = df.groupby(['key1','key2'])['data1'].mean()
s

key1  key2
a     one    -0.289718
      two    -0.813536
b     one     0.332113
      two     0.900853
Name: data1, dtype: float64

In [132]:
s.unstack()

key2       one       two
key1                    
a    -0.289718 -0.813536
b     0.332113  0.900853

3、优化的groupby方法

count 分组中的非NA值数量  
sum 非NA值的累和  
mean 非NA值的均值  
median 非NA值的算术中位数  
std,var 无偏标准差和方差  
min,max 非NA值的最小值，最大值  
first,last 非NA值的第一个和最后一个值

4、需要使用自己的聚合函数，可以将函数传递给agg方法

In [136]:
grouped = df.groupby('key1')
def peak_to_peak(arr):
    return arr.max()-arr.min()#组内最大值与最小值的差
grouped.agg(peak_to_peak)

data1     data2
key1                    
a     0.694097  1.562434
b     0.568740  0.321747

In [137]:
grouped.describe()

data1                                                              \
     count      mean       std       min       25%       50%       75%   
key1                                                                     
a      3.0 -0.464324  0.347069 -0.813536 -0.636767 -0.459998 -0.289718   
b      2.0  0.616483  0.402160  0.332113  0.474298  0.616483  0.758668   

               data2                                                    \
           max count      mean       std       min       25%       50%   
key1                                                                     
a    -0.119439   3.0  0.075334  0.782857 -0.735122 -0.300656  0.133810   
b     0.900853   2.0 -0.278466  0.227509 -0.439339 -0.358903 -0.278466   

                          
           75%       max  
key1                      
a     0.480561  0.827313  
b    -0.198029 -0.117592

5、分组聚合

In [138]:
get_wavg = lambda g: np.average(g['data1'],weights=g['data2'])
df.groupby('key1').apply(get_wavg)

key1
a   -2.861932
b    0.452199
dtype: float64

# 时间序列基础

![hello](../images/p1.jpg)

与时间相关的一般概念：
- 日期时间：带有时区支持的特定日期和时间，例如月、日、年等，又叫时间戳。
- 时间增量：用于操纵日期的绝对时间长度。
- 时间跨度：由时间点及其关联的频率定义的持续时间。
- 日期偏移：涉及日期计算的相对持续时间。

## 基于pandas库

### 时间戳与周期

In [2]:
import pandas as pd
import datetime as dt
import numpy as np

In [3]:
pd.Timestamp(dt.datetime(2014, 5, 1))

Timestamp('2014-05-01 00:00:00')

In [4]:
pd.Timestamp("2014-06-01")

Timestamp('2014-06-01 00:00:00')

In [5]:
pd.Timestamp(2014, 6, 1)

Timestamp('2014-06-01 00:00:00')

In [6]:
pd.Period("2014-06") #M代表月，时间间隔

Period('2014-06', 'M')

In [7]:
pd.Period("2014-06", freq="D")

Period('2014-06-01', 'D')

In [8]:
dates = [
    pd.Timestamp("2014-06-01"),
    pd.Timestamp("2014-06-02"),
    pd.Timestamp("2014-06-03"),
]

ts_data = pd.Series(np.random.randn(3), dates)

type(ts_data.index)

pandas.core.indexes.datetimes.DatetimeIndex

In [9]:
ts_data.index

DatetimeIndex(['2014-06-01', '2014-06-02', '2014-06-03'], dtype='datetime64[ns]', freq=None)

In [10]:
ts_data

2014-06-01   -0.014228
2014-06-02    0.539426
2014-06-03   -1.503673
dtype: float64

pandas使用TimeStamp表示时间戳，使用DatetimeIndex表示时间戳序列。

### 转换为时间戳

In [11]:
pd.to_datetime(pd.Series(["Jul 31, 2012", "2012-01-10", None]))

0   2012-07-31
1   2012-01-10
2          NaT
dtype: datetime64[ns]

### 提供格式参数

In [13]:
pd.to_datetime(["2012/11/23", "2012.12.31"])

DatetimeIndex(['2012-11-23', '2012-12-31'], dtype='datetime64[ns]', freq=None)

In [6]:
pd.to_datetime("2018-11-11 00:00", format="%Y-%m-%d %H:%M")

Timestamp('2018-11-11 00:00:00')

### 时区信息

python是可以包含时区信息的，offset-naive是不含时区的类型，而offset-aware是有时区类型。

- 可以使用 datetime 的 replace 方法添加时区信息，比如 replace(tzinfo=timezone.utc)
- 或者原始的时间字符串就带上时区信息，比如 s = Struct(create_at='1970-01-01 00:00:00+08:00')
- 或者都不带时区信息，可以使用 datetime 的 replace 方法去除时区信息，比如 replace(tzinfo=None)

In [4]:
pd.to_datetime("2018-11-11 00:00", format="%Y-%m-%d %H:%M").replace(tzinfo=None)

Timestamp('2018-11-11 00:00:00')

### 索引

In [79]:
ts_data_load = pd.read_csv("../data/energy_old.csv")

In [80]:
#转换时间格式
ts_data_load["index"] = None
for i in range(ts_data_load.shape[0]):
    year = pd.to_datetime(ts_data_load["Date"][i]).year
    month = pd.to_datetime(ts_data_load["Date"][i]).month
    day = pd.to_datetime(ts_data_load["Date"][i]).day
    hour = ts_data_load["Hour"][i] - 1
    ts_data_load.loc[i, "index"] = pd.Timestamp(year, month, day, hour)
ts_data_load = pd.DataFrame(ts_data_load[["load", "T"]].values, index=ts_data_load["index"].values, columns=["load", "temp"])

In [81]:
ts_data_load.to_csv("../data/energy.csv")

In [82]:
ts_data_load.head()

load   temp
2012-01-01 00:00:00  2698.0  32.00
2012-01-01 01:00:00  2558.0  32.67
2012-01-01 02:00:00  2444.0  30.00
2012-01-01 03:00:00  2402.0  31.00
2012-01-01 04:00:00  2403.0  32.00

In [78]:
ts_data_load.index

DatetimeIndex(['2012-01-01 00:00:00', '2012-01-01 01:00:00',
               '2012-01-01 02:00:00', '2012-01-01 03:00:00',
               '2012-01-01 04:00:00', '2012-01-01 05:00:00',
               '2012-01-01 06:00:00', '2012-01-01 07:00:00',
               '2012-01-01 08:00:00', '2012-01-01 09:00:00',
               ...
               '2014-12-31 14:00:00', '2014-12-31 15:00:00',
               '2014-12-31 16:00:00', '2014-12-31 17:00:00',
               '2014-12-31 18:00:00', '2014-12-31 19:00:00',
               '2014-12-31 20:00:00', '2014-12-31 21:00:00',
               '2014-12-31 22:00:00', '2014-12-31 23:00:00'],
              dtype='datetime64[ns]', length=26304, freq=None)

In [83]:
ts_data_load[::2].index #每隔一小时取值

DatetimeIndex(['2012-01-01 00:00:00', '2012-01-01 02:00:00',
               '2012-01-01 04:00:00', '2012-01-01 06:00:00',
               '2012-01-01 08:00:00', '2012-01-01 10:00:00',
               '2012-01-01 12:00:00', '2012-01-01 14:00:00',
               '2012-01-01 16:00:00', '2012-01-01 18:00:00',
               ...
               '2014-12-31 04:00:00', '2014-12-31 06:00:00',
               '2014-12-31 08:00:00', '2014-12-31 10:00:00',
               '2014-12-31 12:00:00', '2014-12-31 14:00:00',
               '2014-12-31 16:00:00', '2014-12-31 18:00:00',
               '2014-12-31 20:00:00', '2014-12-31 22:00:00'],
              dtype='datetime64[ns]', length=13152, freq=None)

In [86]:
ts_data_load.loc["2012-6-01"] #一天的数据

load   temp
2012-06-01 00:00:00  2474.0  56.67
2012-06-01 01:00:00  2349.0  55.67
2012-06-01 02:00:00  2291.0  54.33
2012-06-01 03:00:00  2281.0  53.00
2012-06-01 04:00:00  2343.0  50.33
2012-06-01 05:00:00  2518.0  49.33
2012-06-01 06:00:00  2934.0  49.33
2012-06-01 07:00:00  3235.0  54.00
2012-06-01 08:00:00  3348.0  57.67
2012-06-01 09:00:00  3405.0  61.00
2012-06-01 10:00:00  3459.0  64.33
2012-06-01 11:00:00  3479.0  66.67
2012-06-01 12:00:00  3478.0  68.67
2012-06-01 13:00:00  3495.0  70.00
2012-06-01 14:00:00  3473.0  70.00
2012-06-01 15:00:00  3439.0  69.00
2012-06-01 16:00:00  3404.0  69.67
2012-06-01 17:00:00  3337.0  67.67
2012-06-01 18:00:00  3291.0  65.00
2012-06-01 19:00:00  3261.0  63.33
2012-06-01 20:00:00  3309.0  63.00
2012-06-01 21:00:00  3197.0  61.67
2012-06-01 22:00:00  2916.0  61.00
2012-06-01 23:00:00  2619.0  60.67

In [89]:
ts_data_load.loc["2012-1":"2012-2-28"]

load   temp
2012-01-01 00:00:00  2698.0  32.00
2012-01-01 01:00:00  2558.0  32.67
2012-01-01 02:00:00  2444.0  30.00
2012-01-01 03:00:00  2402.0  31.00
2012-01-01 04:00:00  2403.0  32.00
...                     ...    ...
2012-02-28 19:00:00  3858.0  28.67
2012-02-28 20:00:00  3687.0  27.33
2012-02-28 21:00:00  3420.0  25.00
2012-02-28 22:00:00  3122.0  24.33
2012-02-28 23:00:00  2875.0  23.00

[1416 rows x 2 columns]

In [90]:
ts_data_load.loc["2012-1":"2012-1-2 00:00:00"]

load   temp
2012-01-01 00:00:00  2698.0  32.00
2012-01-01 01:00:00  2558.0  32.67
2012-01-01 02:00:00  2444.0  30.00
2012-01-01 03:00:00  2402.0  31.00
2012-01-01 04:00:00  2403.0  32.00
2012-01-01 05:00:00  2453.0  31.33
2012-01-01 06:00:00  2560.0  30.00
2012-01-01 07:00:00  2719.0  29.00
2012-01-01 08:00:00  2916.0  29.00
2012-01-01 09:00:00  3105.0  33.33
2012-01-01 10:00:00  3174.0  36.67
2012-01-01 11:00:00  3180.0  40.33
2012-01-01 12:00:00  3184.0  43.67
2012-01-01 13:00:00  3147.0  43.33
2012-01-01 14:00:00  3122.0  45.00
2012-01-01 15:00:00  3137.0  44.67
2012-01-01 16:00:00  3486.0  43.33
2012-01-01 17:00:00  3717.0  41.67
2012-01-01 18:00:00  3659.0  41.33
2012-01-01 19:00:00  3513.0  41.67
2012-01-01 20:00:00  3344.0  42.67
2012-01-01 21:00:00  3129.0  43.33
2012-01-01 22:00:00  2873.0  44.33
2012-01-01 23:00:00  2639.0  44.00
2012-01-02 00:00:00  2458.0  43.67

truncate()函数类似于切片。

In [91]:
ts_data_load.truncate(before="2013-11-01", after="2013-11-02")

load   temp
2013-11-01 00:00:00  2506.0  58.00
2013-11-01 01:00:00  2419.0  57.67
2013-11-01 02:00:00  2369.0  58.00
2013-11-01 03:00:00  2349.0  58.67
2013-11-01 04:00:00  2425.0  59.33
2013-11-01 05:00:00  2671.0  60.00
2013-11-01 06:00:00  3143.0  59.33
2013-11-01 07:00:00  3438.0  59.33
2013-11-01 08:00:00  3486.0  59.67
2013-11-01 09:00:00  3541.0  62.33
2013-11-01 10:00:00  3591.0  63.67
2013-11-01 11:00:00  3585.0  64.67
2013-11-01 12:00:00  3532.0  63.67
2013-11-01 13:00:00  3491.0  63.33
2013-11-01 14:00:00  3430.0  65.67
2013-11-01 15:00:00  3358.0  67.00
2013-11-01 16:00:00  3347.0  67.33
2013-11-01 17:00:00  3478.0  65.67
2013-11-01 18:00:00  3636.0  63.00
2013-11-01 19:00:00  3501.0  60.67
2013-11-01 20:00:00  3345.0  59.67
2013-11-01 21:00:00  3131.0  57.67
2013-11-01 22:00:00  2883.0  57.67
2013-11-01 23:00:00  2626.0  55.67
2013-11-02 00:00:00  2447.0  52.33

### 时间日期组件

![hello](../images/p2.jpg)
![hello](../images/p3.jpg)

### 频率转换

频率转换的主要函数是asfreq()，此方法将时间序列转换为指定的频率，并可选的填充缺失值。

In [96]:
?ts_data_load.asfreq

In [98]:
daily_ts_data = ts_data_load.asfreq(freq='D', method='pad')
daily_ts_data.head(5)

load   temp
2012-01-01  2698.0  32.00
2012-01-02  2458.0  43.67
2012-01-03  2780.0  26.33
2012-01-04  3184.0   6.00
2012-01-05  3014.0  22.33

### 添加时间特征

In [1]:
import pandas as pd

energy = pd.read_csv("../data/energy.csv")
energy.columns = ["time", "load", "temp"]
energy["time"] = pd.to_datetime(energy["time"].values)
energy['month'] = pd.DatetimeIndex(energy['time']).month
energy['year'] = pd.DatetimeIndex(energy['time']).year
energy['day'] = pd.DatetimeIndex(energy['time']).day
energy['year_month_day'] = [str(i)+'-'+str(j)+'-'+str(k) for i,j,k in zip(energy.year, energy.month, energy.day)]
energy.head()

time    load   temp  month  year  day year_month_day
0 2012-01-01 00:00:00  2698.0  32.00      1  2012    1       2012-1-1
1 2012-01-01 01:00:00  2558.0  32.67      1  2012    1       2012-1-1
2 2012-01-01 02:00:00  2444.0  30.00      1  2012    1       2012-1-1
3 2012-01-01 03:00:00  2402.0  31.00      1  2012    1       2012-1-1
4 2012-01-01 04:00:00  2403.0  32.00      1  2012    1       2012-1-1

### 判断时间类型

In [3]:
def is_time_col(dataframe: pd.DataFrame):
    for column, dtype in dataframe.dtypes.items():
        if pd.api.types.is_datetime64_any_dtype(dtype):
            return column
    raise RuntimeError(f"该DataFrame不存在时间列！{dataframe.dtypes}")

In [5]:
time_col = is_time_col(energy)
time_col

'time'

## 基于datetime库

### 标准库

python标准库包含了日期和时间数据的类型，datetime,time,calender模块是开始处理时间数据的主要内容。

In [1]:
from datetime import datetime
now = datetime.now()
now.year

2024

In [141]:
now.month

6

In [142]:
now.day

5

In [7]:
from datetime import timedelta #两个datetime值之差

timedelta的参数
![hello](../images/timedelta.png)

### 字符串与datetime互相转换

In [144]:
s = datetime(2011, 1,1)
str(s)

'2011-01-01 00:00:00'

In [145]:
s.strftime('%F')#传递一个指定的格式给strftime方法

'2011-01-01'

In [146]:
value = '2011-01-03'
datetime.strptime(value, '%Y-%m-%d')#将字符串转换成日期

datetime.datetime(2011, 1, 3, 0, 0)

In [147]:
a = pd.to_datetime(value) #字符串转时间戳
a

Timestamp('2011-01-03 00:00:00')

In [148]:
b = a+timedelta(days=1)
b

Timestamp('2011-01-04 00:00:00')

In [149]:
abs((a-b).days)#相差天数

1

datetime格式说明：  
%Y 四位的年份 %y 两位的年份  
%m 两位的月份 %d 两位的日期号  
%H 24小时制 %I 12小时制  
%F %Y-%m-%d的简写 %D %m/%d/%y的简写

NaT（not a time）是pandas中时间戳数据的null值。

### 截断时间

In [2]:
now = datetime.now()
now

datetime.datetime(2024, 4, 1, 17, 47, 11, 897376)

In [3]:
newdatetime = now.replace(microsecond=0)
newdatetime

datetime.datetime(2024, 4, 1, 17, 47, 11)

## 含有重复索引的时间序列

在某些应用中，可能会有多个数据观察值落在特定的时间戳上，如果要聚合含有非唯一时间戳的数据，一种方式是使用groupby并传递level=0

In [153]:
ts_data_load.groupby(level=0)

## 生成日期范围

pd.date_range()是用于根据特定频率生成指定长度的时间戳，默认情况下，date_range()生成的是每日的时间戳，如果只传递一个起始或结尾日期，必须传递一个用于生成范围的数字（periods=数字）。

In [154]:
ts1 = pd.date_range(start='2012-04-01', end='2013-01-01')
ts1

DatetimeIndex(['2012-04-01', '2012-04-02', '2012-04-03', '2012-04-04',
               '2012-04-05', '2012-04-06', '2012-04-07', '2012-04-08',
               '2012-04-09', '2012-04-10',
               ...
               '2012-12-23', '2012-12-24', '2012-12-25', '2012-12-26',
               '2012-12-27', '2012-12-28', '2012-12-29', '2012-12-30',
               '2012-12-31', '2013-01-01'],
              dtype='datetime64[ns]', length=276, freq='D')

In [155]:
ts2 = pd.date_range(start='2012-04-01', end='2013-01-01', freq='M')#D表示日期的每天，H表示每小时，M表示日历的月底日期
ts2

DatetimeIndex(['2012-04-30', '2012-05-31', '2012-06-30', '2012-07-31',
               '2012-08-31', '2012-09-30', '2012-10-31', '2012-11-30',
               '2012-12-31'],
              dtype='datetime64[ns]', freq='M')

pandas中的频率由基础频率和倍数组成，基础频率通常会有字符串别名，例如：freq='4h'

如果频率已知，则可以将频率传递给shift来推移时间戳，只对时间序列有效，对单个时间戳不能使用，例如：数据名.shift(2,freq='M')

In [8]:
# 生成固定长度的时间范围，按秒生成
length = 100
pd.date_range(start=datetime.now()-timedelta(seconds=length-1), end=datetime.now(), freq='S')

DatetimeIndex(['2024-04-01 17:49:36.191770', '2024-04-01 17:49:37.191770',
               '2024-04-01 17:49:38.191770', '2024-04-01 17:49:39.191770',
               '2024-04-01 17:49:40.191770', '2024-04-01 17:49:41.191770',
               '2024-04-01 17:49:42.191770', '2024-04-01 17:49:43.191770',
               '2024-04-01 17:49:44.191770', '2024-04-01 17:49:45.191770',
               '2024-04-01 17:49:46.191770', '2024-04-01 17:49:47.191770',
               '2024-04-01 17:49:48.191770', '2024-04-01 17:49:49.191770',
               '2024-04-01 17:49:50.191770', '2024-04-01 17:49:51.191770',
               '2024-04-01 17:49:52.191770', '2024-04-01 17:49:53.191770',
               '2024-04-01 17:49:54.191770', '2024-04-01 17:49:55.191770',
               '2024-04-01 17:49:56.191770', '2024-04-01 17:49:57.191770',
               '2024-04-01 17:49:58.191770', '2024-04-01 17:49:59.191770',
               '2024-04-01 17:50:00.191770', '2024-04-01 17:50:01.191770',
               '2024-04-0

## Series.dt的用法

1、dt.date和dt.normalize()都返回一个日期的日期部分，只包含年月日，先创建一个DataFrame名为df。

In [156]:
df = pd.DataFrame({'time':['2020-07-12 20:59:37', '2020-07-13 20:59:37']})
df

time
0  2020-07-12 20:59:37
1  2020-07-13 20:59:37

In [161]:
pd.to_datetime(df['time']).dt.date

0    2020-07-12
1    2020-07-13
Name: time, dtype: object

2、dt.year,dt.month,dt.day,dt.hour,dt.minute,dt.second,dt.week,分别返回年月日时分秒

In [162]:
pd.to_datetime(df['time']).dt.day

0    12
1    13
Name: time, dtype: int64

3、dt.weekday 返回一周中的星期几，0代表星期一，6代表星期天

4、dt.dayofyear 返回一年的第几天  
dt.quarter 返回每个日期分别是第几个季度

5、dt.is_month_start,dt.is_month_end 判断是否为每月的第一天或最后一天  
dt.is_year_start,dt.is_year_end 判断是否为每年的第一天或最后一天   
dt.is_quarter_start,dt.is_quarter_end 判断是否为每季度的第一天或最后一天 

dt.is_leap_year 判断是否为闰年

dt.month_name() 返回月份的英文名称

6、dt.days 返回时间差 (pd.to_datetime(字符串1)-pd.to_datetime(字符串2)).dt.days

7、重新采样是指将时间序列从一个频率转换为另一个时间频率的过程，将更高频率的数据聚合到低频率被称为向下采样，而从低频率向高频率称为向上采样。pandas拥有resample()方法，先调用resample对数据分组，之后再调用聚合函数。

data.resample('频率').聚合函数 频率可以为'D','5min'等，聚合函数包括sum()，mean()等。

# broadcast（广播机制）

广播”指的是在不同维度的数组之间进行算术运算的一种执行机制，其通过将数据矢量化进行高效的运算。

在panda中广播操作是指一个Series数组和另一个DataFrame进行运算，举例如下：

In [30]:
import pandas as pd
a = pd.Series([0,1,2])
b = pd.DataFrame([[0,0,0],[10,10,10],[20,20,20],[30,30,30]],
                 index=['A','B','C','D'])
print(a)

0    0
1    1
2    2
dtype: int64


In [31]:
print(b)

    0   1   2
A   0   0   0
B  10  10  10
C  20  20  20
D  30  30  30


In [32]:
print(a + b)

    0   1   2
A   0   1   2
B  10  11  12
C  20  21  22
D  30  31  32


从结果上来看是很神奇的，从原理上来说就是a进行了维度的扩展，变成了[[0,1,2], [0,1,2], [0,1,2], [0,1,2]]，然后与b进行相加的操作。示意图如下：

当然了其他的运算也会有同样的效果：

In [34]:
c = pd.Series([0.1,0.2,0.3])
d = 10
print(c*d)

0    1.0
1    2.0
2    3.0
dtype: float64


In [35]:
print(c/10)

0    0.01
1    0.02
2    0.03
dtype: float64


维度不一致的时候，会怎样呢？

In [36]:
import pandas as pd

a_1 = pd.Series([0,1])
b_1 = pd.DataFrame([[0,0,0],[10,10,10],[20,20,20],[30,30,30]],
                 index=['A','B','C','D'])
print(a_1 + b_1)

      0     1   2
A   0.0   1.0 NaN
B  10.0  11.0 NaN
C  20.0  21.0 NaN
D  30.0  31.0 NaN


结果还是很好理解的，总维度与高维度的数据维度一致。

# 其他

## 缺失值判定

Pandas中的空值有三个：**np.nan (Not a Number) 、 None 和 pd.NaT**(时间格式的空值，注意大小写不能错)，这三个值可以用Pandas中的函数isnull()，notnull()，isna()进行判断。

### np.isnan()

- np.nan不是一个“空”对象，用 i is None判断是False；
- 对某个值是否为空值进行判断，只能用np.isnan(i)函数，万万不可用 i == np.nan()来做，因为空值并不能用判断相等的“==”正确识别（上例前两条）；
- np.nan非空对象，其类型为基本数据类型float
- 需要注意的是，使用isnan()函数检测np.nan时，需要保证数组元素的类型是浮点数。如果元素类型是其他类型，会抛出TypeError的异常

In [9]:
# np.nan()的一些奇妙性质：
np.nan == np.nan

False

In [10]:
type(np.nan)

float

In [11]:
np.nan is None

False

In [12]:
np.isnan(np.nan)

True

### pd.isnull()

In [13]:
# 首先创建一个DataFrame：
bb = pd.DataFrame({'a':[0,1,2,np.nan]})
bb

a
0  0.0
1  1.0
2  2.0
3  NaN

In [14]:
# 先测试一下np.isnan()
np.isnan(bb)

a
0  False
1  False
2  False
3   True

In [15]:
# 值得一提的是，如果想获悉整个DataFrame有无空值，可以在此基础上这样做：
np.isnan(bb).all()

a    False
dtype: bool

In [16]:
# 再测试一下isnull()
pd.isnull(bb)

a
0  False
1  False
2  False
3   True

在实际应用中，np.isnan()多用于单个值的检验，pd.isnull()用于对一个DataFrame或Series（整体）的检验。

## pandas常用配置

通过pandas的使用，我们经常要交互式地展示表格（dataframe）、分析表格。而表格的格式就显得尤为重要了，因为大部分时候如果我们直接展示表格，格式并不是很友好。

其实呢，这些痛点都可以通过pandas的option来解决。短短几行代码，只要提前配置好，一次设置好，全局生效

pd.set_option('') #设置配置

pd.get_option('') #获得配置

pd.reset_option('') #重置

### 显示更多行

默认情况下，pandas 是不超出屏幕的显示范围的，如果表的行数很多，它会截断中间的行只显示一部分。我们可以通过设置display.max_rows来控制显示的最大行数，比如我想设置显示200行。

In [3]:
pd.set_option('display.max_rows', 200)

如果行数超过了display.max_rows，那么display.min_rows将确定显示的部分有多少行。因为display.min_rows的默认行数为5，,下面例子只显示前5行和最后5行，中间的所有行省略。

In [4]:
pd.set_option('display.min_rows', 10)

In [5]:
# 重置
pd.reset_option('display.max_rows')

### 显示更多列

行可以设置，同样的列也可以设置，display.max_columns控制着可显示的列数，默认值为20。

In [7]:
pd.set_option('display.max_columns', 30) 

###  改变列宽

pandas对列中显示的字符数有一些限制，默认值为50字符。所以，有的值字符过长就会显示省略号。如果想全部显示，可以设置display.max_colwidth，比如设置成500。

In [8]:
pd.set_option ('display.max_colwidth',500)

### 设置float列的精度

对于float浮点型数据，pandas默认情况下只显示小数点后6位。我们可以通过预先设置display.precision让其只显示2位，避免后面重复操作。

In [9]:
pd.set_option( 'display.precision',2)

这个设置不影响底层数据，它只影响浮动列的显示。

### 数字格式化显示

pandas中有一个选项display.float_formatoption可以用来格式化任何浮点列。这个仅适用于浮点列，对于其他数据类型，必须将它们转换为浮点数才可以。

例如 1200000 这样的大数字看起来很不方便，所以我们用逗号进行分隔。

In [10]:
pd.set_option('display.float_format','{:,}'.format)

假如我们只关心小数点后的2位数字，我们可以这样设置格式化：

In [11]:
pd.set_option('display.float_format',  '{:,.2f}'.format)

如果我们要显示一个百分比的列，可以这样设置。

In [12]:
pd.set_option('display.float_format', '{:.2f}%'.format)

### 更改绘图方法

默认情况下，pandas使用matplotlib作为绘图后端。从 0.25 版本开始，pandas提供了使用不同后端选择，比如plotly，bokeh等第三方库，但前提是你需要先安装起来。

### 配置info()的输出

pandas中我们经常要使用info()来快速查看DataFrame的数据情况。但是，info这个方法对要分析的最大列数是有默认限制的，并且如果数据集中有null，那么在大数据集计数统计时会非常慢。

pandas提供了两种选择：

- display.max_info_columns: 设置要分析的最大列数，默认为100。
- display.max_info_rows: 设置计数null时的阈值，默认为1690785。

比如，在分析有 150 个特征的数据集时，我们可以设置display.max_info_columns为涵盖所有列的值，比如将其设置为 200：

In [14]:
pd.set_option('display.max_info_columns', 200)

只在行数不超过5时才计数null：

In [15]:
pd.set_option('display.max_info_rows', 5)

### 打印出当前设置并重置所有选项

pd.describe_option()将打印出设置的描述及其当前值。

In [16]:
pd.describe_option()

compute.use_bottleneck : bool
    Use the bottleneck library to accelerate if it is installed,
    the default is True
    Valid values: False,True
    [default: True] [currently: True]
compute.use_numba : bool
    Use the numba engine option for select operations if it is installed,
    the default is False
    Valid values: False,True
    [default: False] [currently: False]
compute.use_numexpr : bool
    Use the numexpr library to accelerate computation if it is installed,
    the default is True
    Valid values: False,True
    [default: True] [currently: True]
display.chop_threshold : float or None
    if set to a float value, all float values smaller than the given threshold
    will be displayed as exactly 0 by repr and friends.
    [default: None] [currently: None]
display.colheader_justify : 'left'/'right'
    Controls the justification of column headers. used by DataFrameFormatter.
    [default: right] [currently: right]
display.date_dayfirst : boolean
    When True, prints an

### 全部重置

In [17]:
pd.reset_option('all')

C:\Users\IKAS\AppData\Local\Temp\ipykernel_34000\2786130087.py:1: FutureWarning: use_inf_as_na option is deprecated and will be removed in a future version. Convert inf values to NaN before operating instead.
  pd.reset_option('all')


# 滑动窗口

提供滑动窗口计算，可用于时间序列（时间和日期）数据  
`DataFrame.rolling(window, min_periods=None, center=False, win_type=None, on=None, axis=0, closed=None, method='single')`

参数：

- **window**：int, offset, or BaseIndexer subclass
移动窗口的大小，如果是整数，代表每个窗口覆盖的固定数量；如果是offset（pandas时间序列），代表每个窗口的时间段，每个窗口的大小将根据时间段中包含的观察值而变化，仅对datetimelike索引有效。
- **min_periods**：int, default None
窗口计算值要求至少有min_periods个观测值。窗口由时间类型指定，则min_periods默认为1，窗口为整数，则min_periods默认为窗口大小
- **center**：bool, default False
是否将窗口中间索引设为窗口计算后的标签
- **win_type**：str, default None
观测值的权重分布。如果为None，则所有点的权重均相等。如果是字符串，要求是 scipy.signal window function函数
- **on**：str, optional
对于 DataFrame，计算滚动窗口所依照的列标签或索引级别，而不是 DataFrame 的索引
- **axis**：int or str, default 0
如果是0或’index’，按行滚动；如果是1或’columns’，按列滚动
- **closed**：str, default None
‘right’：窗口中的第一个点将从计算中排除；‘left‘：窗口中的最后一个点将从计算中排除；‘both’：窗口中没有点将从计算中排除；‘neither’：窗口中的第一个点和最后一个点将从计算中排除；默认’right’

In [2]:
df = pd.DataFrame({'B': [i for i in range(5)]})
df

B
0  0
1  1
2  2
3  3
4  4

In [3]:
df.rolling(window=2).sum() # 前两个点的总和

B
0  NaN
1  1.0
2  3.0
3  5.0
4  7.0