# 代码计时

## time.time()

返回当前时间的时间戳 如 1524302633.980187  
两次时间相减，代码运行所需的 挂钟时间，也就是命令开始执行到结束的时间。

In [2]:
import time
start = time.time()
print("Hello World")
end = time.time()
print(end - start)

Hello World
0.0


## timeit

In [4]:
from timeit import timeit
timeit('[i for i in range(100) if i%2==0]', number=10000)

0.04830319999928179

In [5]:
def func(a):
    sum = 0
    for i in range(a):
        sum += i
    return sum

timeit('func(10000000)', 'from __main__ import func', number=1)

0.5664076999992176

# 类型提示

众所周知，Python 是动态类型语言，运行时不需要指定变量类型。这一点是不会改变的，但是2015年9月创始人 Guido van Rossum 在 Python 3.5 引入了一个类型系统，允许开发者指定变量类型–类型提示（Type Hints）。它的主要作用是方便开发，供IDE 和各种开发工具使用，对代码运行不产生影响，运行时会过滤类型信息。

## 优点

1、易于理解代码
指定函数输入和输出，便于理解代码片段的过程。
有了类型提示（Type Hints），在调用函数时就可以告诉你需要传递哪些参数类型；以及需要扩展/修改函数时，也会告诉你输入和输出所需要的数据类型。 

2、 易于重构
类型提示可以在重构时，更好得帮助我们定位类的位置。

虽然许多IDE现在采用一些启发式方法提供了这项功能，但是类型提示可以使IDE具有100%的检测准确率，并定位到类的位置。这样可以更平滑，更准确地检测变量类型在代码中的运行方式。

请记住，虽然动态类型意味着任何变量都可以成为任何类型，但是所有变量在所有时间中都应只有一种类型。类型系统仍然是编程的核心组件，想想那些使用isinstance判断变量类型、应用逻辑所浪费的时间吧。

3、 易于使用库
使用类型提示意味着IDE可以拥有更准确、更智能的建议引擎。当调用自动完成时，IDE会完全放心地知道对象上有哪些方法/属性可用。此外，如果用户尝试调用不存在的内容或传递不正确类型的参数，IDE可以立即警告它。

4、验证运行数据
类型标注（Type annotations）是一种直接的方式，并且是类型文档中最常见到的那种方式。

使用：语句将信息附加到变量或函数参数中。
->运算符用于将信息附加到函数/方法的返回值中。

## 类型标注

类型标注（Type annotations）是一种直接的方式，并且是类型文档中最常见到的那种方式。
声明一个函数参数的类型，只要在参数名称的后面加个":“号，带上类型名称就行了。声明函数的返回值类型，只要在函数声明结束之前，也就是”:“号之前加入一个”->"，带上类型名称。

常见数据类型

- int,long,float: 整型,长整形,浮点型
- bool,str: 布尔型，字符串类型
- List, Tuple, Dict, Set:列表，元组，字典, 集合
- Iterable,Iterator:可迭代类型，迭代器类型
- Generator：生成器类型

### 基本数据类型

In [2]:
def test(a: int, b: str) -> str:
    print(a, b)
    return 1000


if __name__ == '__main__':
    test('test', 'abc')

test abc


只是提出了警告，但实际上运行是不会报错，毕竟python的本质还是动态语言。

### 复杂的类型标注

In [3]:
from typing import List
Vector = List[float]

def scale(scalar: float, vector: Vector) -> Vector:
    return [scalar * num for num in vector]

# typechecks; a list of floats qualifies as a Vector.
new_vector = scale(2.0, [1.0, -4.2, 5.4])

In [6]:
from typing import Dict, Tuple, Sequence

ConnectionOptions = Dict[str, str]
Address = Tuple[str, int]
Server = Tuple[Address, ConnectionOptions]

def broadcast_message(message: str, servers: Sequence[Server]) -> None:
    ...

# The static type checker will treat the previous type signature as
# being exactly equivalent to this one.
def broadcast_message(
    message: str,
    servers: Sequence[Tuple[Tuple[str, int], Dict[str, str]]]) -> None:
    pass

### 泛型指定

In [7]:
from typing import Sequence, TypeVar, Union

T = TypeVar('T')      # Declare type variable

def first(l: Sequence[T]) -> T:   # Generic function
    return l[0]

T = TypeVar('T')  # Can be anything
A = TypeVar('A', str, bytes)  # Must be str or bytes
A = Union[str, None] # Must be str or None

In [9]:
# 创建变量时类型指定
from typing import NamedTuple

class Employee(NamedTuple):
    name: str
    id: int = 3

employee = Employee('Guido')
assert employee.id == 3

Optional，可选类型， Optional[X] 等价于 X | None （或 Union[X, None] ）。 意思是说这个参数可以为空或已经声明的类型。

但值得注意的是，这个并不等价于可选参数，当它作为参数类型注解的时候，不代表这个参数可以不传递了，而是说这个参数可以传为 None。

In [1]:
#Optional
from typing import Optional

def foo_v2(a: int, b: Optional[int] = None):
    if b:
        print(a + b)
    else:
        print("parameter b is a NoneType!")

#只传入a位置的实参
foo_v2(2)

parameter b is a NoneType!


### 参数注释

In [11]:
def send_mail(
    sender: "fish@example.com", receiver: "panda@example.com",
    subject: "say hello to you.", message: "hello.",
    attachments: list("type<io.BytesIO>")) -> bool:
    return sender

In [14]:
send_mail("dog@example.com", "panda@example.com", "panda@example.com", "panda@example.com", "panda@example.com")

'dog@example.com'

写在":“号后面的并一定是一个类型。Python把这种写法称为"annotations”(标注)，在运行的时候完全不使用它。它是专门设计出来给程序员和自动处理程序看的。任何可被计算出来的东西都可以写在那里。

很明显，与直接写类型相比，直接把参数是什么样子写出来更容易让调用者看清楚函数的使用方法。更激进的话，标注还可以是被计算出来的。

In [15]:
def add_matrix3x3(
    x: [(1, 1, 1), (1, 1, 1), (1, 1, 1)],
    y: [(2, 2, 2), (2, 2, 2), (2, 2, 2)],
) -> [(3, 3, 3), (3, 3, 3), (3, 3, 3)]:
    pass

## 不足之处

In [16]:
from typing import List


def test(b: List[int]) -> str:
    print(b)
    return 'test'


if __name__ == '__main__':
    test([1, 'a'])

[1, 'a']


从这个例子可以看出来，虽然我们指定了List[int]即由int组成的列表，但是，实际中，只要这个列表中存在int（其他的可以为任何类型），就不会出现警告。

# 类型推断

isinstance() 函数来判断一个对象是否是一个已知的类型，类似 type()。

isinstance() 与 type() 区别：

- type() 不会认为子类是一种父类类型，不考虑继承关系。

- isinstance() 会认为子类是一种父类类型，考虑继承关系。

如果要判断两个类型是否相同推荐使用 isinstance()。

以下是 isinstance() 方法的语法:

isinstance(object, classinfo)

参数
- object -- 实例对象。
- classinfo -- 可以是直接或间接类名、基本类型或者由它们组成的元组。

如果对象的类型与参数二的类型（classinfo）相同则返回 True，否则返回 False。

## 单类型

In [17]:
a = 2
isinstance (a,int)

True

In [18]:
isinstance (a,str)

False

## 多类型

In [19]:
isinstance (a,(str,int,list))    # 是元组中的一个返回 True

True

对于基本类型来说 classinfo 可以是：

int，float，bool，complex，str(字符串)，list，dict(字典)，set，tuple

要注意的是，classinfo 的字符串是 str 而不是 string，字典也是简写 dict。

## None

In [27]:
isinstance(None, type(None))

True

In [28]:
isinstance(None, (type(None), list, str))

True

# python脚本

## `__init__.py`

在Python工程里，当python检测到一个目录下存在__init__.py文件时，python就会把它当成一个模块(module)。Module跟C＋＋的命名空间和Java的Package的概念很像，都是为了科学地组织化工程，管理命名空间。

__init__.py可以是一个空文件，也可以有非常丰富的内容。本文将举一个非常简单的例子，来介绍__init__.py的用法.

__init__.py 会在 import 的时候被执行，而空的 __init__.py 在Python新版本中已经不需要你额外去定义了，因为就算你不定义 init， Python 也知道你导入的包路径，但是如果你想要做一些初始化操作，或者像我们刚刚说的预先导入相关的模块，那么定义 __init__.py 还是很有必要的

[https://zhuanlan.zhihu.com/p/115350758](相关网址)

## python文件中执行另一个python文件

在python文件中直接执行另一个python文件，和引用（import）其他python文件的方法函数有所不同，相当于直接Run python文件

使用 os.system()

print.py为另一个python文件

# .npy文件

.npy文件是numpy专用的二进制文件。在深度神经网络训练过程中通常需要读取预训练权重，预训练权重通常是 .npy文件。

## 读取与保存

In [1]:
import numpy as np

arr = np.array([[1, 2, 3],
               [4, 5, 6]])
np.save('../data/weight.npy', arr)

loadData = np.load('../data/weight.npy')

print("----type----")
print(type(loadData))
print("----shape----")
print(loadData.shape)
print("----data----")
print(loadData)

----type----
<class 'numpy.ndarray'>
----shape----
(2, 3)
----data----
[[1 2 3]
 [4 5 6]]


# jupyter运行命令行命令

根据操作系统的不同可分linux命令和cmd命令，语法和对应命令完全相同，只是**每句前面都要加一个英文感叹号**。linux命令在colab，kaggle等云端环境非常常见，因为云端只能操作notebook，但很多人不知道cmd命令也是可以的。另外，conda命令也是可以执行的，因此一份notebook可以包含从建立虚拟环境，到编辑代码，到创建py脚本，最后用命令行执行脚本的全过程。

In [1]:
!conda env list

# conda environments:
#
base                  *  D:\Anaconda



In [5]:
%%writefile ../data/main.py
# 本地创建一个main.py文件，并填入代码
import numpy as np
a=np.array([1,2,3])
print(a)

Overwriting ../data/main.py


In [6]:
!python ../data/main.py

[1 2 3]


# argsparse

argsparse是python的命令行解析的标准模块，内置于python，不需要安装。这个库可以让我们直接在命令行中就可以向程序中传入参数并让程序运行。

## 传入一个参数

先在本地文件夹中新建demo.py文件

In [7]:
%%writefile ../data/demo.py
import argparse

parser = argparse.ArgumentParser(description='命令行中传入一个数字')
#type是要传入的参数的数据类型  help是该参数的提示信息
parser.add_argument('integers', type=str, help='传入的数字')

args = parser.parse_args()

#获得传入的参数
print(args)

Writing ../data/demo.py


然后在命令行中输入python demo.py -h或者python demo.py --help

In [9]:
!python ../data/demo.py -h

usage: demo.py [-h] integers

命令行中传入一个数字

positional arguments:
  integers    传入的数字

options:
  -h, --help  show this help message and exit


在命令行中看到demo.py的运行结果如下

现在我们在命令行中给demo.py 传入一个参数5，

In [10]:
!python ../data/demo.py 5

Namespace(integers='5')


## 操作args字典

其实得到的这个结果Namespace(integers='5')是一种类似于python字典的数据类型。

我们可以使用 arg.参数名来提取这个参数

In [11]:
%%writefile ../data/demo1.py
import argparse

parser = argparse.ArgumentParser(description='命令行中传入一个数字')
#type是要传入的参数的数据类型  help是该参数的提示信息
parser.add_argument('integers', type=str, help='传入的数字')

args = parser.parse_args()

#获得传入的参数
print(args.integers)

Writing ../data/demo1.py


In [12]:
!python ../data/demo1.py 5

5


## 传入多个参数

In [13]:
%%writefile ../data/demo2.py
import argparse

parser = argparse.ArgumentParser(description='命令行中传入一个数字')
parser.add_argument('integers', type=str, nargs='+',help='传入的数字')
args = parser.parse_args()

print(args.integers)

Writing ../data/demo2.py


nargs是用来说明传入的参数个数，'+' 表示传入至少一个参数。

In [16]:
!python ../data/demo2.py 5 4 3

['5', '4', '3']


## 改变数据类型

type这个关键词可以传入list, str, tuple, set, dict等。

## 位置参数

在命令行中传入参数时候，传入的参数的先后顺序不同，运行结果往往会不同，这是因为采用了位置参数,例如

In [17]:
%%writefile ../data/demo3.py
import argparse

parser = argparse.ArgumentParser(description='姓名')
parser.add_argument('param1', type=str,help='姓')
parser.add_argument('param2', type=str,help='名')
args = parser.parse_args()

#打印姓名
print(args.param1+args.param2)

Writing ../data/demo3.py


In [18]:
!python ../data/demo3.py 张 三

张三


## 可选参数

为了在命令行中避免上述位置参数的bug（容易忘了顺序），可以使用可选参数，这个有点像关键词传参，但是需要在关键词前面加--，例如

In [19]:
%%writefile ../data/demo4.py
import argparse

parser = argparse.ArgumentParser(description='姓名')
parser.add_argument('--family', type=str,help='姓')
parser.add_argument('--name', type=str,help='名')
args = parser.parse_args()

#打印姓名
print(args.family+args.name)

Writing ../data/demo4.py


In [20]:
!python ../data/demo4.py --family=张 --name=三

张三


## 默认值

add_argument中有一个default参数。有的时候需要对某个参数设置默认值，即如果命令行中没有传入该参数的值，程序使用默认值。如果命令行传入该参数，则程序使用传入的值。具体请看下面的例子

In [21]:
%%writefile ../data/demo5.py
import argparse

parser = argparse.ArgumentParser(description='姓名')
parser.add_argument('--family', type=str, default='张',help='姓')
parser.add_argument('--name', type=str, default='三', help='名')
args = parser.parse_args()

#打印姓名
print(args.family+args.name)

Writing ../data/demo5.py


In [22]:
!python ../data/demo5.py

张三


In [24]:
!python ../data/demo5.py --family=李

李三


## 必须参数

add_argument有一个required参数可以设置该参数是否必需。

In [29]:
%%writefile ../data/demo6.py
import argparse

parser = argparse.ArgumentParser(description='姓名')
parser.add_argument('--family', type=str, default='张', help='姓')
parser.add_argument('--name', type=str, required=True, default='', help='名')
args = parser.parse_args()

#打印姓名
print(args.family+args.name)

Overwriting ../data/demo6.py


In [30]:
!python ../data/demo6.py --family=李

usage: demo6.py [-h] [--family FAMILY] --name NAME
demo6.py: error: the following arguments are required: --name


In [31]:
!python ../data/demo6.py --name=四

张四
