<font face="微软雅黑" color=green size=5>Python数据分析</font>

# numpy基础

numpy的核心特征之一就是N维数组对象ndarray，ndarray是python中一个快速，灵活的大型数据集容器，它包含的每一个元素均为相同类型。

In [2]:
import numpy as np

shape 用来表征数组每一维度的数量 数组名.shape  
dtype 用来描述数组的数据类型 数组名.dtype  
ndim 用来查看维度

## 生成数组

array() np.array(变量名) np.array(list) 将列表转换成数组  
zeros() 一次性创造全是0的数组 np.zeros(数字) 一维 np.zeros((n, m)) n×m数组  
ones() 一次性创造全是1的数组  用法同zeros()  
empty() 创建一个没有初始化数值的数组 用法同zeros()  

## 索引与切片

一维数组  
数组名[n] 索引n处的值，一维数组索引与列表相同，可看成是列表  
数组名[n:m] 索引n到m-1处的值，如果是高维，返回n到m-1行的数组  

二维数组，每个索引值对应的元素不再是一个值，而是一个一维数组    
数组名[n][m] 单个元素n,m处  
数组名[n,m] 单个元素n,m处  
数组名[n] 第n行元素

多维数组  
数组名[n] 返回的对象是一个降低一个维度的数组，每个平面的第n行组成的二维数组  
数组名[n,m] 返回一个一维数组  
数组名[n1:n2, m1:m2] 返回n1到n2-1行，m1到m2-1列的数组  

## 神奇索引

为了选出一个符合特定顺序的子集，可以通过传递一个包含指明所需顺序的列表或数组来完成。  
数组名[[n]] 提取第n行的数组  
数组名[[n1,n2,n3]] 提取索引为n1,n2,n3行的数组  
数组名[[n1,n2,n3],[m1,m2,m3]] 提取索引为(n1,m1),(n2,m2),(n3,m3)的元素

## 数组转置

数组名.T  
矩阵内积 np.dot(arr.T,arr)  
arange python内建函数range的数组版，返回一个数组，np.arange(n) n从0开始，到n-1结束。  
transpose 置换轴

## 通用函数

np.sqrt(数组名) 开方  
np.exp(数组名) 指数  
np.square(数组名) 平方  
np.add(x,y) 加  
np.multiply() 乘  
np.divide() 除  
np.where(条件,数组1,数组2) 类似三元表达式   
np.nan 代表NaN

In [3]:
arr = np.random.randn(4,4)
np.where(arr>0, 2, -2)

array([[-2, -2, -2, -2],
       [-2,  2,  2, -2],
       [ 2,  2, -2, -2],
       [-2,  2, -2,  2]])

## 数学与统计方法

数组名.sum(axis=0或1) 或np.sum(数组名) 求和   
数组名.mean() 平均值  
数组名.std() 标准差  
数组名.var() 方差  
axis=0 对行进行操作，等价于DataFrame中 axis='index'  
axis=1 对列进行操作，等价于DataFrame中 axis='columns'  
axis=i 沿着第i个下标变化的方向进行操作   
数组名.sort() 或np.sort(数组名) 排序升序  
np.argsort(数组名) 返回排序后的索引  
np.sort(数组名)[::-1] 降序排列  
np.flipub(数组名) 翻转元组，也可以用数组名[::-1]
np.random.seed(1) 随机种子  
np.random.rand((n,m)) 从均匀分布中抽取样本生成n×m的数组  
np.random.randn((n,m)) 从标准正态分布中抽取样本生成n×m的数组 

## 重塑数组

很多情况下，将数组从一个形状转换为另一个形状，并且不复制任何数据，可以用reshape方法。

In [5]:
arr = np.arange(8)
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [6]:
arr.reshape((4,2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

将更高维的数组转换为一维数组（扁平化、分散化）。

In [7]:
arr.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7])

In [8]:
arr.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7])

## 复制数组

np.tile() 把数组沿各个方向复制

In [9]:
a = np.array([0,1,2])
np.tile(a,(2,1)) #把a先沿x轴复制1倍，再把结果沿y轴复制两倍

array([[0, 1, 2],
       [0, 1, 2]])

In [10]:
np.tile(a, 2) #沿x轴复制2倍

array([0, 1, 2, 0, 1, 2])

np.linspace() 创建等差数列

In [11]:
np.linspace(0,10,11) #第一个起始值，第二个终点值，第三个数量

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

## 连接和分割数组

1、np.concatenate() 可以获取数组的序列，并沿着输入轴将他们按顺序连接在一起。

In [13]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[7,8,9],[10,11,12]])
np.concatenate([arr1,arr2],axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [14]:
np.concatenate([arr1,arr2],axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

2、split可以将数组沿轴向切片成多个数组。

In [16]:
np.split(arr1,[1,2]) #[1,2]表示将数组拆分时的索引位置

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([], shape=(0, 3), dtype=int32)]

3、数组后面追加数组

In [17]:
np.append(arr1,arr2,axis=0) #按行追加

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

## broadcast（广播机制）

广播”指的是在不同维度的数组之间进行算术运算的一种执行机制，其通过将数据矢量化进行高效的运算。

通常只在对多个数组进行对应元素操作形状不同时，才会发生广播。
那什么是对应元素进行操作呢？比如：

In [5]:
a = np.array([1,2,3])
b = np.array([2,2,2])
a*b 
# a和b对应元素相乘
# a*b的结果是： [1*2,2*2,3*2]

array([2, 4, 6])

什么叫做形状不同呢？

In [7]:
a = np.array([1,2,3])
b = 2
a*b #a是1维向量，b是标量，这就是形状不同
# 结果也是：[1*2,2*2, 3*2]

array([2, 4, 6])

这是因为发生了广播。b被填充为[2,2,2]
然后a\*b的效果变成了，[1,2,3]*[2,2,2]

可以广播的几种情况：

假定只有两个数组进行操作，即A+B、A*B这种情况。

**两个数组各维度大小从后往前比对均一致**

In [8]:
A = np.zeros((2,5,3,4))
B = np.zeros((3,4))
print((A+B).shape) # 输出 (2, 5, 3, 4)

A = np.zeros((4))
B = np.zeros((3,4))
print((A+B).shape) # 输出(3,4)

(2, 5, 3, 4)
(3, 4)


In [9]:
A = np.zeros((2,5,3,4))
B = np.zeros((3,3))
print((A+B).shape)

ValueError: operands could not be broadcast together with shapes (2,5,3,4) (3,3) 

为啥呢？因为最后一维的大小A是4，B是3，不一致。

**两个数组存在一些维度大小不相等时，有一个不相等数组的维度大小为1**

In [10]:
A = np.zeros((2,5,3,4))
B = np.zeros((3,1))
print((A+B).shape) # 输出：(2, 5, 3, 4)

A = np.zeros((2,5,3,4))
B = np.zeros((2,1,1,4))
print((A+B).shape) # 输出：(2, 5, 3, 4)

A = np.zeros((1))
B = np.zeros((3,4))
print((A+B).shape) # 输出(3,4)

(2, 5, 3, 4)
(2, 5, 3, 4)
(3, 4)


In [11]:
# 下面是报错案例
A = np.zeros((2,5,3,4))
B = np.zeros((2,4,1,4))
print((A+B).shape)

ValueError: operands could not be broadcast together with shapes (2,5,3,4) (2,4,1,4) 

为啥报错？因为A和B的第2维不相等。并且都不等于1.

**使用numpy的广播机制代替for循环以提高效率**

In [17]:
def contrast(n,f,k):
    import time
    data = np.random.rand(n, f)
    centers = data[:k]
    t1 = time.time()
    c1 = (data[:,:,None]-centers.T[None,:,:])**2
    t2 = time.time()
    print('cost of broadcast: ',str(t2-t1))
    c2 = np.ones((n,f,k))-1
    t1 = time.time()
    for i in range(n):
        for j in range(f):
            for g in range(k):
                c2[i,j,g] = (data[i,j]-centers[g,j])**2
    t2 = time.time()
    print('cost of _for_: ',str(t2-t1))
    print('c2 - c1 == 0?: ',str((c2-c1).all()==0))

def test_time_cost(n,f,k):
    contrast(n,f,k)

if __name__ == '__main__':
    test_time_cost(200000,5,10)

cost of broadcast:  0.042083740234375
cost of _for_:  4.9777257442474365
c2 - c1 == 0?:  True


## 数组增加维度

np.newaxis的作用就是在这一位置增加一个一维，这一位置指的是np.newaxis所在的位置

In [19]:
a = np.array([0.0, 10.0, 20.0, 30.0])
print(a.shape)
b = a[:, np.newaxis]
print(b.shape)
c = a[np.newaxis, :]
print(c.shape)

(4,)
(4, 1)
(1, 4)


### newaxis本质

np.newaxis 在使用和功能上等价于 None，其实就是 None 的一个别名。

In [20]:
type(np.newaxis)

NoneType

In [21]:
np.newaxis == None

True

In [22]:
b = a[:, np.newaxis]
b

array([[ 0.],
       [10.],
       [20.],
       [30.]])

In [23]:
b = a[:, None]
b

array([[ 0.],
       [10.],
       [20.],
       [30.]])

### 索引多维数组的某一列时返回的是一个行向量

In [24]:
X = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
X[:, 1] #这里是一个行

array([ 2,  6, 10])

如果我索引多维数组的某一列时，返回的仍然是列的结构，一种正确的索引方式是：

In [25]:
X[:, 1][:, np.newaxis]

array([[ 2],
       [ 6],
       [10]])

如果想实现第二列和第四列的拼接（层叠）：

In [26]:
X_sub = np.hstack([X[:, 1][:, np.newaxis], X[:, 3][:, np.newaxis]])   
X_sub

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

当然更为简单的方式还是使用切片：

In [27]:
X[:, [1, 3]]

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

# Pandas入门

pandas采用了很多numpy的代码风格，但最大的不同在于pandas是用来处理表格型或异质型数据的，而numpy更适合处理同质型的数值类数组数据。

In [4]:
import pandas as pd
from pandas import DataFrame, Series

## Series

Series是一种一维的数组型对象，它包含了一个值序列，并且包含了数据标签，成为索引，最简单的序列可以仅仅由一个数组组成。

In [2]:
obj = pd.Series([4,7,-5,3], index = ['d','b','a','c'])
obj

d    4
b    7
a   -5
c    3
dtype: int64

交互式环境中Series的字符串表示，索引在左边，值在右边，可通过values属性和index属性分别获得Series对象的值和索引。

In [3]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [4]:
obj.index

Index(['d', 'b', 'a', 'c'], dtype='object')

可以使用字典生成一个Series，pd.Series(字典)。

Series的索引可以通过按位置赋值的方式进行改变，obj.index = [值]。

## DataFrame

DataFrame表示的是矩阵的数据表，它包含已排序的列集合，每一列可以是不同的值类型，DataFrame既有行索引，也有列索引，DataFrame是二维的。

### 构建DataFrame

有多种方式构建DataFrame，其中最常用的是利用包含等长度列表或numpy数组的字典来形成。行索引（index），列索引（columns），值（values）。

In [7]:
data = {'state':['ohio', 'ohio', 'nevada'],
        'year':[2000, 2001, 2002]}
frame = pd.DataFrame(data)
frame

state  year
0    ohio  2000
1    ohio  2001
2  nevada  2002

### DataFrame切片

1、DataFrame的列会按照指定顺序排列，如果你指定了列的顺序。

In [8]:
pd.DataFrame(data, columns = ['year', 'state'])

year   state
0  2000    ohio
1  2001    ohio
2  2002  nevada

2、DataFrame中的一列，可以按照字典型标记，或属性那样检索为Series。

In [9]:
frame['state']

0      ohio
1      ohio
2    nevada
Name: state, dtype: object

3、行可以通过位置或特殊属性loc进行选取。

In [10]:
frame.loc[0]

state    ohio
year     2000
Name: 0, dtype: object

4、列的引用可以修改，可以对列赋值为标量或值数组，如果被赋值的列不存在，则会生成一个新列。

In [14]:
frame['debt'] = 16.5
frame

state  year  debt
0    ohio  2000  16.5
1    ohio  2001  16.5
2  nevada  2002  16.5

5、del关键字可以像在字典中那样删除列。

In [15]:
del frame['debt']
frame

state  year
0    ohio  2000
1    ohio  2001
2  nevada  2002

In [16]:
frame.T #转置

0     1       2
state  ohio  ohio  nevada
year   2000  2001    2002

6、DataFrame的values属性会将包含在DataFrame中的数据以二维数组的形式返回。

In [17]:
frame.values

array([['ohio', 2000],
       ['ohio', 2001],
       ['nevada', 2002]], dtype=object)

In [18]:
frame.columns #列索引

Index(['state', 'year'], dtype='object')

In [19]:
frame.index #行索引

RangeIndex(start=0, stop=3, step=1)

7、pandas索引对象可以包含重复标签。

In [20]:
labels = pd.Index(['foo','foo','bar','bar'])

8、显示DataFrame的行数

In [21]:
frame.head(2)

state  year
0  ohio  2000
1  ohio  2001

### 重建索引

reindex是pandas对象的重要方法，该方法用于创建一个符合新索引的新对象。（标签唯一）

In [23]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6],index = ['d', 'b', 'a', 'c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [24]:
obj.reindex(['a', 'b', 'c', 'd'])

a   -5.3
b    7.2
c    3.6
d    4.5
dtype: float64

series调用reindex方法时，会将数据按照新的索引（行索引或列索引）进行排列，如果某个索引值之前并不存在，则会引入缺失值。

### 轴向上删除条目

drop方法会返回一个含有指示值或轴向上删除值的新对象。

In [28]:
obj = pd.Series(np.arange(5.),index = ['a','b','c','d','e'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [29]:
obj.drop('c')

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

在DataFrame中，索引值可以轴向上删除，在调用drop时使用标签序列会根据行标签删除值。名字.drop(行标签)

可以通过传递axis=1或axis='columns'来从列中删除值。

名字.drop(列名,axis=1)#删除这一列  
名字.drop([,,],axis='columns')#删除多列

### 索引，选择与过滤

1、Series的索引与Numpy数组索引的功能类似。

In [30]:
obj = pd.Series(np.arange(4),index = ['a','b','c','d'])
obj

a    0
b    1
c    2
d    3
dtype: int32

In [31]:
obj['b']

1

In [32]:
obj[1]

1

In [33]:
obj[2:4]

c    2
d    3
dtype: int32

2、使用单个值或序列，可以从DataFrame中索引出一个或多个列。

In [34]:
data = {'state':['ohio', 'ohio', 'nevada'],
        'year':[2000, 2001, 2002]}
frame = pd.DataFrame(data)
frame

state  year
0    ohio  2000
1    ohio  2001
2  nevada  2002

In [35]:
frame['year'] #索引单个列

0    2000
1    2001
2    2002
Name: year, dtype: int64

In [36]:
frame[['year','state']] #索引多个列

year   state
0  2000    ohio
1  2001    ohio
2  2002  nevada

3、使用布尔值DataFrame进行索引，布尔值DataFrame可以是对标量值进行比较产生。

data[data>5]=0  将大于5的变为0，其余不变

4、通过标签选出单行多列或多行多列的数据，轴标签loc，整数标签iloc。

frame.loc[行标签,列标签]

In [39]:
frame.loc[0,'year']#单行单列

2000

In [40]:
frame.loc[0,['year','state']]#单行多列

year     2000
state    ohio
Name: 0, dtype: object

In [41]:
frame.loc[[0,1],'year']#多行单列

0    2000
1    2001
Name: year, dtype: int64

frame.iloc[行索引值,列索引值]

In [42]:
frame.iloc[0,0]

'ohio'

### 算术与数据对齐

1、add 加 sub 减 div 除 mul乘  
a.add(b,axis=0) 行相加

2、函数应用和映射

In [48]:
f = lambda x: x.count()
frame.apply(f,axis='columns') #以列作为索引的Series，默认是axis=0

0    2
1    2
2    2
dtype: int64

3、排序

如需按行或列索引进行排序，需要使用sort_index方法，默认为升序排列。

In [49]:
frame.sort_index()#按行索引

state  year
0    ohio  2000
1    ohio  2001
2  nevada  2002

In [51]:
frame.sort_index(axis=1, ascending=False)#按列索引并且降序排列

year   state
0  2000    ohio
1  2001    ohio
2  2002  nevada

如需根据Series的值进行排序，使用sort_values方法。当对DataFrame排序时，可以使用一列或多列作为排序键，使用参数by实现。

In [53]:
frame.sort_values(by='year',ascending=False)

state  year
2  nevada  2002
1    ohio  2001
0    ohio  2000

In [54]:
list(frame) #获得表头

['state', 'year']

### 描述性统计

pandas对象装配了一个常用数学，统计学方法的集合，与numpy中的类似方法相比，它们内建了处理缺失值的功能，NA值会被自动排除。

In [56]:
frame.sum(axis=0) #行相加

state    ohioohionevada
year               6003
dtype: object

In [57]:
frame.describe()#描述性统计

year
count     3.0
mean   2001.0
std       1.0
min    2000.0
25%    2000.5
50%    2001.0
75%    2001.5
max    2002.0

常见方法：count\min\max\sum\mean\median\var\std

In [59]:
frame.apply(pd.value_counts).fillna(0) #计算不同值在每个列中出现的次数

state  year
2000      0.0   1.0
2001      0.0   1.0
2002      0.0   1.0
nevada    1.0   0.0
ohio      2.0   0.0

### 数据类型转换

In [60]:
frame.dtypes #查看数据框的类型

state    object
year      int64
dtype: object

In [61]:
frame.info() #查看数据框的更多详细信息

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   state   3 non-null      object
 1   year    3 non-null      int64 
dtypes: int64(1), object(1)
memory usage: 176.0+ bytes


pandas三种常用的数据格式的转换：   
1、名字.astype()强制转化为数据类型  
2、通过创建自定义的函数进行数据转换  
3、pandas提供的to_numeric()以及to_datetime()

In [79]:
frame['year'] = frame['year'].astype('int')#将DataFrame中的某一列转换类型
frame

state  year
0    ohio  2000
1    ohio  2001
2  nevada  2002

### DataFrame拼接

In [91]:
data1 = {'state':['nace','eque'],
        'year':[2003,2004]}
frame1 = pd.DataFrame(data1)
frame1

state  year
0  nace  2003
1  eque  2004

In [92]:
frame.append(frame1, ignore_index=True) #忽略列名，只显示一个，也可用循环实现

state  year
0    ohio  2000
1    ohio  2001
2  nevada  2002
3    nace  2003
4    eque  2004

In [93]:
pd.concat([frame,frame1], axis=0)#横向拼接

state  year
0    ohio  2000
1    ohio  2001
2  nevada  2002
0    nace  2003
1    eque  2004

### 时间序列/差分

In [94]:
frame.shift(1)

state    year
0   NaN     NaN
1  ohio  2000.0
2  ohio  2001.0

frame.shift(periods=1, freq=None, axis=0) periods类型为int，表示移动的幅度，可以是正数，也可以是负数，默认值为1，1表示移动一次，这里移动的是数据，而索引是不移动的，移动之后没有对应值的，为NaN。

freq可选参数，只适用于时间序列，如果这个参数存在，会按照参数值移动时间索引，而数据值没有发生变化。

### 抽样

frame.sample(n=None, frac=None, replace=False, weights=None, random_state=None, axis=None)  
n：设置抽样数量  
frac：设置抽样比例  
replace：设置是否放回  
weights：设置样本权重  
random_state：设置随机种子

In [97]:
frame.sample(frac=0.5)

state  year
0  ohio  2000
1  ohio  2001

# 数据载入、存储和文件格式

## 基本操作

1、将表格型数据读取为DataFrame对象是pandas的重要特征，read_csv和read_table是使用最多的函数。

`df = pd.read_csv('文件名', sep=',', header=None, chunksize=1000, encoding='gbk')`  
sep用于分隔每行字段的字符序列  
header显示列名  
encoding 显示文字类型 gbk表示中文  
chunksize用于迭代的块的大小

2、将数据写入文本格式  

`frame.to_csv('路径',sep=' ', na_rep='NULL', index=False, header=False, columns=[,,], mode='a')  `  
sep=' '空格形式写入  
na_rep 对缺失值进行标注  
columns 按照选定的顺序写入  
mode='a' 不覆盖追加数据

3、读入其他数据

Json数据 pd.read_json()  
Html数据 pd.read_html()  
Excel数据 pd.read_excel('路径','表名') 数据名称.to_excel('路径','表名')

4、数据库读数

In [98]:
import pymysql

具体见mysql数据库.ipynb资料

## 遍历文件夹及其子目录

In [99]:
import os

os.listdir(path) 返回指定的文件夹包含的文件或文件夹的名字的列表

os.walk(top, topdown=True, onerror=None, followlinks=False)  
top是你要遍历的目录的地址  
topdown为真，优先遍历top目录，否则优先遍历top的子目录  
followlinks为真，会遍历目录下的快捷方式  

os.walk的返回值是一个生成器，需要不断遍历，每次遍历的对象都是返回一个三元组(root, dirs, files)  
root：当前目录  
dirs：该文件夹中所有的目录的名字 list格式  
files：该文件夹中的所有文件 list格式  
每次用next()取得一个返回值。

os.path_join(path1,path2,...) 把目录和文件名合成一个路径  
os.mkdir(path) 创建一个目录  

In [101]:
import shutil

suhtil.copyfile(src, dst) 将src文件内容复制到dst文件中

# 数据清洗与准备

## 处理缺失值

pandas对象的所有描述性统计信息默认情况下是排除缺失值(NA)。

1、NA处理方法  
dropna() 返回所有的非空数据  
fillna() 用某些值填充缺失的数据或使用插值方法  
isnull() 返回表名哪些值是缺失值的布尔值  
notnull() isnull()的反函数  

In [102]:
frame.isnull().any() #判断哪些列存在缺失值

state    False
year     False
dtype: bool

In [103]:
frame.isnull().sum(axis=1) #返回每行缺失值总数

0    0
1    0
2    0
dtype: int64

In [104]:
frame.isnull().sum(axis=0) #返回每列缺失值总数

state    0
year     0
dtype: int64

2、np.nan表示缺失值或 from numpy import nan as NA，用NA代替缺失值

3、当处理DataFrame对象时，dropna默认情况下会删除包含缺失值的行  
dropna(how='all') 删除所有值均为NA的行  
dropna(axis=1) 删除包含缺失值的列

## 补全缺失值

1、大多数情况下，主要使用fillna()来补全缺失值，可以使用一个常数来替代缺失值。

In [105]:
frame.fillna(0)

state  year
0    ohio  2000
1    ohio  2001
2  nevada  2002

2、在调用fillna时使用字典，可以为不同列设定不同的填充值。

In [106]:
frame.fillna({1:0.5, 2:0.7}) #第二列缺失值填充为0.5，第三列填充为0.7

state  year
0    ohio  2000
1    ohio  2001
2  nevada  2002

3、可以将平均值、中位数等函数计算结果用于填充缺失值。

In [107]:
frame.fillna(frame.mean())

state  year
0    ohio  2000
1    ohio  2001
2  nevada  2002

## 删除重复值

In [108]:
frame.drop_duplicates() #去除重复行

state  year
0    ohio  2000
1    ohio  2001
2  nevada  2002

In [109]:
frame.drop_duplicates(['state']) #基于指定列去除重复值

state  year
0    ohio  2000
2  nevada  2002

## 替代值

In [110]:
frame.replace(2000,np.nan)

state    year
0    ohio     NaN
1    ohio  2001.0
2  nevada  2002.0

In [111]:
frame.replace([2000,1000],[np.nan,0]) #多值替代

state    year
0    ohio     NaN
1    ohio  2001.0
2  nevada  2002.0

## 重命名轴索引

In [113]:
frame.rename(index={0:'zero',1:'one',2:'two'}, columns={'year':'years','state':'states'})

states  years
zero    ohio   2000
one     ohio   2001
two   nevada   2002

## 离散化和分箱

In [114]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]
bins = [18, 25, 35, 60, 100]#将年龄划分区间
cuts = pd.cut(ages, bins)
cuts

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [115]:
pd.value_counts(cuts)#统计区间个数

(18, 25]     5
(25, 35]     3
(35, 60]     3
(60, 100]    1
dtype: int64

In [116]:
pd.qcut(ages, 4)#将样本按四分位数切成四分

[(19.999, 22.75], (19.999, 22.75], (22.75, 29.0], (22.75, 29.0], (19.999, 22.75], ..., (29.0, 38.0], (38.0, 61.0], (38.0, 61.0], (38.0, 61.0], (29.0, 38.0]]
Length: 12
Categories (4, interval[float64]): [(19.999, 22.75] < (22.75, 29.0] < (29.0, 38.0] < (38.0, 61.0]]

# 重塑和透视

分层索引是pandas的重要特性，允许你在一个轴向上拥有多个索引层级，分层索引提供了一种在更低维度的形式中处理更高维度数据的方式。

In [119]:
frame.unstack() #拆堆

state  0      ohio
       1      ohio
       2    nevada
year   0      2000
       1      2001
       2      2002
dtype: object

In [120]:
frame.stack() #堆叠

0  state      ohio
   year       2000
1  state      ohio
   year       2001
2  state    nevada
   year       2002
dtype: object

# 绘图和可视化

## matplotlib库

In [117]:
import matplotlib as plt

## seaborn库

In [118]:
import seaborn as sns

# 数据聚合与分组操作

## groupby机制

DataFrame可以在它的行方向（axis=0）或列方向（axis=1）进行分组，在这种情况下，你可以传递列名或行名（无论它们是字符串、数字或其他python对象）作为分组键。

In [122]:
df = pd.DataFrame({'key1':['a','a','b','b','a'],
                   'key2':['one','two','one','two','one'],
                   'data1':np.random.randn(5),
                   'data2':np.random.randn(5)})
df

key1 key2     data1     data2
0    a  one -0.119439 -0.735122
1    a  two -0.813536  0.827313
2    b  one  0.332113 -0.439339
3    b  two  0.900853 -0.117592
4    a  one -0.459998  0.133810

1、根据key1标签计算data1的均值  

In [123]:
df.groupby('key1')['data1'].mean()

key1
a   -0.464324
b    0.616483
Name: data1, dtype: float64

2、根据key1，key2标签进行分组

In [124]:
df.groupby(['key1', 'key2'])

上述语句现在是一个groupby对象，需要迭代产生结果。

In [128]:
#当只有一个标签时：
for name, group in df.groupby('key1'):
    print(name)
    print(group)

a
  key1 key2     data1     data2
0    a  one -0.119439 -0.735122
1    a  two -0.813536  0.827313
4    a  one -0.459998  0.133810
b
  key1 key2     data1     data2
2    b  one  0.332113 -0.439339
3    b  two  0.900853 -0.117592


In [129]:
#当只有两个标签时：
for (k1,k2),group in df.groupby(['key1','key2']):
    print((k1,k2))
    print(group)

('a', 'one')
  key1 key2     data1     data2
0    a  one -0.119439 -0.735122
4    a  one -0.459998  0.133810
('a', 'two')
  key1 key2     data1     data2
1    a  two -0.813536  0.827313
('b', 'one')
  key1 key2     data1     data2
2    b  one  0.332113 -0.439339
('b', 'two')
  key1 key2     data1     data2
3    b  two  0.900853 -0.117592


根据key1，key2标签对data1进行分组，并求均值。

In [131]:
s = df.groupby(['key1','key2'])['data1'].mean()
s

key1  key2
a     one    -0.289718
      two    -0.813536
b     one     0.332113
      two     0.900853
Name: data1, dtype: float64

In [132]:
s.unstack()

key2       one       two
key1                    
a    -0.289718 -0.813536
b     0.332113  0.900853

3、优化的groupby方法

count 分组中的非NA值数量  
sum 非NA值的累和  
mean 非NA值的均值  
median 非NA值的算术中位数  
std,var 无偏标准差和方差  
min,max 非NA值的最小值，最大值  
first,last 非NA值的第一个和最后一个值

4、需要使用自己的聚合函数，可以将函数传递给agg方法

In [136]:
grouped = df.groupby('key1')
def peak_to_peak(arr):
    return arr.max()-arr.min()#组内最大值与最小值的差
grouped.agg(peak_to_peak)

data1     data2
key1                    
a     0.694097  1.562434
b     0.568740  0.321747

In [137]:
grouped.describe()

data1                                                              \
     count      mean       std       min       25%       50%       75%   
key1                                                                     
a      3.0 -0.464324  0.347069 -0.813536 -0.636767 -0.459998 -0.289718   
b      2.0  0.616483  0.402160  0.332113  0.474298  0.616483  0.758668   

               data2                                                    \
           max count      mean       std       min       25%       50%   
key1                                                                     
a    -0.119439   3.0  0.075334  0.782857 -0.735122 -0.300656  0.133810   
b     0.900853   2.0 -0.278466  0.227509 -0.439339 -0.358903 -0.278466   

                          
           75%       max  
key1                      
a     0.480561  0.827313  
b    -0.198029 -0.117592

5、分组聚合

In [138]:
get_wavg = lambda g: np.average(g['data1'],weights=g['data2'])
df.groupby('key1').apply(get_wavg)

key1
a   -2.861932
b    0.452199
dtype: float64

# 时间序列

时间戳是指具体的时刻，时间间隔由开始和结束的时间戳表示，最简单和最广泛使用的时间序列是那些由时间戳索引的。

## 标准库

python标准库包含了日期和时间数据的类型，datetime,time,calender模块是开始处理时间数据的主要内容，python中没有时间格式，有时间戳格式即**datetime**。

In [5]:
from datetime import datetime
now = datetime.now()
now.year

2022

In [141]:
now.month

6

In [142]:
now.day

5

In [143]:
from datetime import timedelta #两个datetime值之差

## 字符串与datetime互相转换

In [144]:
s = datetime(2011, 1,1)
str(s)

'2011-01-01 00:00:00'

In [145]:
s.strftime('%F')#传递一个指定的格式给strftime方法

'2011-01-01'

In [146]:
value = '2011-01-03'
datetime.strptime(value, '%Y-%m-%d')#将字符串转换成日期

datetime.datetime(2011, 1, 3, 0, 0)

In [147]:
a = pd.to_datetime(value) #字符串转时间戳
a

Timestamp('2011-01-03 00:00:00')

In [148]:
b = a+timedelta(days=1)
b

Timestamp('2011-01-04 00:00:00')

In [149]:
abs((a-b).days)#相差天数

1

datetime格式说明：  
%Y 四位的年份 %y 两位的年份  
%m 两位的月份 %d 两位的日期号  
%H 24小时制 %I 12小时制  
%F %Y-%m-%d的简写 %D %m/%d/%y的简写

NaT（not a time）是pandas中时间戳数据的null值。

## 时间序列基础

pandas中的基础时间序列种类是由时间戳索引的Series。

In [151]:
ts = pd.Series(np.random.randn(1000),index=pd.date_range('1/1/2000',periods=1000))
ts

2000-01-01    0.049483
2000-01-02    0.893562
2000-01-03   -0.277230
2000-01-04    0.260456
2000-01-05   -1.157175
                ...   
2002-09-22   -0.729083
2002-09-23    1.051229
2002-09-24    0.752375
2002-09-25   -0.829323
2002-09-26    1.121126
Freq: D, Length: 1000, dtype: float64

In [152]:
ts['2001-08']#切片

2001-08-01   -1.256517
2001-08-02   -1.395781
2001-08-03    0.748102
2001-08-04   -0.872823
2001-08-05    0.728484
2001-08-06   -0.435993
2001-08-07   -0.445153
2001-08-08   -0.551603
2001-08-09   -1.057061
2001-08-10    1.381218
2001-08-11   -0.745560
2001-08-12   -0.465090
2001-08-13    0.699410
2001-08-14    1.054398
2001-08-15   -0.635825
2001-08-16    1.411235
2001-08-17   -0.184278
2001-08-18    0.032061
2001-08-19   -2.664003
2001-08-20   -0.823069
2001-08-21    0.538735
2001-08-22   -2.116020
2001-08-23   -0.280585
2001-08-24   -0.427736
2001-08-25    0.322519
2001-08-26   -0.579885
2001-08-27    1.519428
2001-08-28   -0.127343
2001-08-29    0.349665
2001-08-30    0.667901
2001-08-31   -1.255139
Freq: D, dtype: float64

## 含有重复索引的时间序列

在某些应用中，可能会有多个数据观察值落在特定的时间戳上，如果要聚合含有非唯一时间戳的数据，一种方式是使用groupby并传递level=0

In [153]:
ts.groupby(level=0)

## 生成日期范围

pd.date_range()是用于根据特定频率生成指定长度的时间戳，默认情况下，date_range()生成的是每日的时间戳，如果只传递一个起始或结尾日期，必须传递一个用于生成范围的数字（periods=数字）。

In [154]:
ts1 = pd.date_range(start='2012-04-01', end='2013-01-01')
ts1

DatetimeIndex(['2012-04-01', '2012-04-02', '2012-04-03', '2012-04-04',
               '2012-04-05', '2012-04-06', '2012-04-07', '2012-04-08',
               '2012-04-09', '2012-04-10',
               ...
               '2012-12-23', '2012-12-24', '2012-12-25', '2012-12-26',
               '2012-12-27', '2012-12-28', '2012-12-29', '2012-12-30',
               '2012-12-31', '2013-01-01'],
              dtype='datetime64[ns]', length=276, freq='D')

In [155]:
ts2 = pd.date_range(start='2012-04-01', end='2013-01-01', freq='M')#D表示日期的每天，H表示每小时，M表示日历的月底日期
ts2

DatetimeIndex(['2012-04-30', '2012-05-31', '2012-06-30', '2012-07-31',
               '2012-08-31', '2012-09-30', '2012-10-31', '2012-11-30',
               '2012-12-31'],
              dtype='datetime64[ns]', freq='M')

pandas中的频率由基础频率和倍数组成，基础频率通常会有字符串别名，例如：freq='4h'

如果频率已知，则可以将频率传递给shift来推移时间戳，只对时间序列有效，对单个时间戳不能使用，例如：数据名.shift(2,freq='M')

## Series.dt的用法

1、dt.date和dt.normalize()都返回一个日期的日期部分，只包含年月日，先创建一个DataFrame名为df。

In [156]:
df = pd.DataFrame({'time':['2020-07-12 20:59:37', '2020-07-13 20:59:37']})
df

time
0  2020-07-12 20:59:37
1  2020-07-13 20:59:37

In [161]:
pd.to_datetime(df['time']).dt.date

0    2020-07-12
1    2020-07-13
Name: time, dtype: object

2、dt.year,dt.month,dt.day,dt.hour,dt.minute,dt.second,dt.week,分别返回年月日时分秒

In [162]:
pd.to_datetime(df['time']).dt.day

0    12
1    13
Name: time, dtype: int64

3、dt.weekday 返回一周中的星期几，0代表星期一，6代表星期天

4、dt.dayofyear 返回一年的第几天  
dt.quarter 返回每个日期分别是第几个季度

5、dt.is_month_start,dt.is_month_end 判断是否为每月的第一天或最后一天  
dt.is_year_start,dt.is_year_end 判断是否为每年的第一天或最后一天   
dt.is_quarter_start,dt.is_quarter_end 判断是否为每季度的第一天或最后一天 

dt.is_leap_year 判断是否为闰年

dt.month_name() 返回月份的英文名称

6、dt.days 返回时间差 (pd.to_datetime(字符串1)-pd.to_datetime(字符串2)).dt.days

7、重新采样是指将时间序列从一个频率转换为另一个时间频率的过程，将更高频率的数据聚合到低频率被称为向下采样，而从低频率向高频率称为向上采样。pandas拥有resample()方法，先调用resample对数据分组，之后再调用聚合函数。

data.resample('频率').聚合函数 频率可以为'D','5min'等，聚合函数包括sum()，mean()等。

# broadcast（广播机制）

广播”指的是在不同维度的数组之间进行算术运算的一种执行机制，其通过将数据矢量化进行高效的运算。

在panda中广播操作是指一个Series数组和另一个DataFrame进行运算，举例如下：

In [30]:
import pandas as pd
a = pd.Series([0,1,2])
b = pd.DataFrame([[0,0,0],[10,10,10],[20,20,20],[30,30,30]],
                 index=['A','B','C','D'])
print(a)

0    0
1    1
2    2
dtype: int64


In [31]:
print(b)

    0   1   2
A   0   0   0
B  10  10  10
C  20  20  20
D  30  30  30


In [32]:
print(a + b)

    0   1   2
A   0   1   2
B  10  11  12
C  20  21  22
D  30  31  32


从结果上来看是很神奇的，从原理上来说就是a进行了维度的扩展，变成了[[0,1,2], [0,1,2], [0,1,2], [0,1,2]]，然后与b进行相加的操作。示意图如下：

当然了其他的运算也会有同样的效果：

In [34]:
c = pd.Series([0.1,0.2,0.3])
d = 10
print(c*d)

0    1.0
1    2.0
2    3.0
dtype: float64


In [35]:
print(c/10)

0    0.01
1    0.02
2    0.03
dtype: float64


维度不一致的时候，会怎样呢？

In [36]:
import pandas as pd

a_1 = pd.Series([0,1])
b_1 = pd.DataFrame([[0,0,0],[10,10,10],[20,20,20],[30,30,30]],
                 index=['A','B','C','D'])
print(a_1 + b_1)

      0     1   2
A   0.0   1.0 NaN
B  10.0  11.0 NaN
C  20.0  21.0 NaN
D  30.0  31.0 NaN


结果还是很好理解的，总维度与高维度的数据维度一致。