In [6]:
import pandas as pd
from sklearn.linear_model import Lasso, LassoCV
from sklearn.preprocessing import StandardScaler
# 糖尿病数据集
from sklearn.datasets import load_diabetes
diabetes = load_diabetes()

X = diabetes.data           # data
y = diabetes.target         # label

sd=StandardScaler()
X=sd.fit_transform(X)
coefs=[]

for alpha in [0.01,0.05,0.1,0.5,1]:
    lr=Lasso(alpha=alpha)
    lr.fit(X,y)
    coefs.append(lr.coef_)

coefs=pd.DataFrame(coefs)

In [7]:
coefs

0          1          2          3          4          5          6  \
0 -0.453186 -11.386067  24.736086  15.407660 -36.052455  21.424062   4.029853   
1 -0.361460 -11.302888  24.774197  15.320704 -29.546206  16.418589   0.926383   
2 -0.277693 -11.159488  24.855184  15.242133 -26.448140  13.725663  -0.000000   
3 -0.000000 -10.288091  24.983901  14.668772  -7.761369  -0.000000  -8.449715   
4 -0.000000  -9.319413  24.831276  14.088706  -4.838928  -0.000000 -10.622799   

          7          8         9  
0  8.136614  35.147572  3.213283  
1  6.995393  32.801456  3.199715  
2  7.055574  31.575062  3.158477  
3  3.284326  24.953043  2.907029  
4  0.000000  24.420811  2.562130

In [9]:
import numpy as np
lr=LassoCV(alphas=np.linspace(0,1,100),cv=3)
lr.fit(X,y)
print(lr.alpha_) #这里的alpha为最佳的alpha值
print(lr.mse_path_) #输出每一个alpha对应的交叉验证的mse的值

0.26262626262626265
[[3077.62254261 3210.66142358 2803.20178143]
 [3077.09403092 3210.99257542 2803.15588531]
 [3076.45436151 3211.30177261 2803.10360482]
 [3075.8274465  3211.61180408 2803.05382472]
 [3075.19178074 3211.92385603 2803.01293082]
 [3074.5701238  3212.23774792 2802.96562884]
 [3073.93992639 3212.5534898  2802.92743222]
 [3073.32360784 3212.87108133 2802.88296234]
 [3072.6988971  3213.19052251 2802.84161554]
 [3072.08792038 3213.51181334 2802.82853019]
 [3071.46869712 3213.83495383 2802.81632008]
 [3070.86306238 3214.15994397 2802.805229  ]
 [3070.24932661 3214.48678377 2802.78883565]
 [3069.64903387 3214.81547322 2802.78235939]
 [3069.0407856  3215.11710736 2802.77683474]
 [3068.44583485 3215.29207552 2802.7724834 ]
 [3067.84307408 3215.46923831 2802.62655347]
 [3067.25346532 3215.65179746 2802.42125085]
 [3066.65619205 3215.83828724 2802.21009254]
 [3066.07192529 3216.02838431 2802.00317065]
 [3065.48013952 3216.22202067 2801.80650485]
 [3064.90121475 3216.41918204 2801.

D:\Anaconda\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:614: UserWarning: Coordinate descent without L1 regularization may lead to unexpected results and is discouraged. Set l1_ratio > 0 to add L1 regularization.
  model = cd_fast.enet_coordinate_descent_gram(
D:\Anaconda\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:614: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 417645.6432900219, tolerance: 177.11073333333334
  model = cd_fast.enet_coordinate_descent_gram(
D:\Anaconda\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:614: UserWarning: Coordinate descent without L1 regularization may lead to unexpected results and is discouraged. Set l1_ratio > 0 to add L1 regularization.
  model = cd_fast.enet_coordinate_descent_gram(
D:\Anaconda\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:614: ConvergenceWarning: Objective did not converge. You might want to increas